// Code generated by gowrap. DO NOT EDIT.
// template: ../../../templates/opentelemetry.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package store

//go:generate gowrap gen -p github.com/sarathsp06/sparrow/internal/webhooks/store -i RepositoryInterface -t ../../../templates/opentelemetry.tmpl -o RepositoryInterface_otel.go -l ""

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	_codes "go.opentelemetry.io/otel/codes"
)

// RepositoryInterfaceWithTracing implements RepositoryInterface interface instrumented with open telemetry spans
type RepositoryInterfaceWithTracing struct {
	RepositoryInterface
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]interface{})
}

// NewRepositoryInterfaceWithTracing returns RepositoryInterfaceWithTracing
func NewRepositoryInterfaceWithTracing(base RepositoryInterface, instance string, spanDecorator ...func(span trace.Span, params, results map[string]interface{})) RepositoryInterfaceWithTracing {
	d := RepositoryInterfaceWithTracing{
		RepositoryInterface: base,
		_instance:           instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// AggregateHealthSummaries implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) AggregateHealthSummaries(ctx context.Context) (i1 int, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.AggregateHealthSummaries")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx}, map[string]interface{}{
				"i1":  i1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.AggregateHealthSummaries(ctx)
}

// CalculateWebhookHealth implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) CalculateWebhookHealth(ctx context.Context, webhookID uuid.UUID, lookbackHours int) (s1 string, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.CalculateWebhookHealth")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":           ctx,
				"webhookID":     webhookID,
				"lookbackHours": lookbackHours}, map[string]interface{}{
				"s1":  s1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.CalculateWebhookHealth(ctx, webhookID, lookbackHours)
}

// CreateDelivery implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) CreateDelivery(ctx context.Context, delivery *WebhookDelivery) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.CreateDelivery")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"delivery": delivery}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.CreateDelivery(ctx, delivery)
}

// CreateSubscription implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) CreateSubscription(ctx context.Context, sub *EventSubscription) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.CreateSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"sub": sub}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.CreateSubscription(ctx, sub)
}

// DeleteEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) DeleteEvent(ctx context.Context, eventName string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.DeleteEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"eventName": eventName}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.DeleteEvent(ctx, eventName)
}

// DeleteSubscription implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) DeleteSubscription(ctx context.Context, id uuid.UUID) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.DeleteSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.DeleteSubscription(ctx, id)
}

// GetDeliveriesByEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetDeliveriesByEvent(ctx context.Context, eventID uuid.UUID) (wpa1 []*WebhookDelivery, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetDeliveriesByEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"eventID": eventID}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetDeliveriesByEvent(ctx, eventID)
}

// GetDeliveriesByWebhook implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetDeliveriesByWebhook(ctx context.Context, webhookID uuid.UUID) (wpa1 []*WebhookDelivery, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetDeliveriesByWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetDeliveriesByWebhook(ctx, webhookID)
}

// GetDeliveriesByWebhookID implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetDeliveriesByWebhookID(ctx context.Context, webhookID uuid.UUID, namespace string, limit int, offset int) (wpa1 []*WebhookDelivery, i1 int, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetDeliveriesByWebhookID")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"namespace": namespace,
				"limit":     limit,
				"offset":    offset}, map[string]interface{}{
				"wpa1": wpa1,
				"i1":   i1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetDeliveriesByWebhookID(ctx, webhookID, namespace, limit, offset)
}

// GetDeliveryByID implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetDeliveryByID(ctx context.Context, deliveryID uuid.UUID, namespace string) (wp1 *WebhookDelivery, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetDeliveryByID")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"deliveryID": deliveryID,
				"namespace":  namespace}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetDeliveryByID(ctx, deliveryID, namespace)
}

// GetEventByID implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetEventByID(ctx context.Context, eventID uuid.UUID) (ep1 *EventRecord, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetEventByID")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"eventID": eventID}, map[string]interface{}{
				"ep1": ep1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetEventByID(ctx, eventID)
}

// GetEventByName implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetEventByName(ctx context.Context, eventName string) (ep1 *EventRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetEventByName")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"eventName": eventName}, map[string]interface{}{
				"ep1": ep1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetEventByName(ctx, eventName)
}

// GetEventDeliveryStats implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetEventDeliveryStats(ctx context.Context, eventID uuid.UUID) (i1 int32, i2 int32, i3 int32, i4 int32, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetEventDeliveryStats")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"eventID": eventID}, map[string]interface{}{
				"i1":  i1,
				"i2":  i2,
				"i3":  i3,
				"i4":  i4,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetEventDeliveryStats(ctx, eventID)
}

// GetNamespaceStats implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetNamespaceStats(ctx context.Context, namespace string) (np1 *NamespaceStats, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetNamespaceStats")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"namespace": namespace}, map[string]interface{}{
				"np1": np1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetNamespaceStats(ctx, namespace)
}

// GetHealthSummary implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetHealthSummary(ctx context.Context) (m1 map[WebhookHealth]int, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetHealthSummary")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx}, map[string]interface{}{
				"m1":  m1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetHealthSummary(ctx)
}

// GetRetriableDeliveries implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetRetriableDeliveries(ctx context.Context, webhookID uuid.UUID, namespace string, force bool) (wpa1 []*WebhookDelivery, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetRetriableDeliveries")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"namespace": namespace,
				"force":     force}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetRetriableDeliveries(ctx, webhookID, namespace, force)
}

// GetSubscription implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetSubscription(ctx context.Context, id uuid.UUID) (ep1 *EventSubscription, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"id":  id}, map[string]interface{}{
				"ep1": ep1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetSubscription(ctx, id)
}

// GetSubscriptionsWithWebhooksByEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetSubscriptionsWithWebhooksByEvent(ctx context.Context, namespace string, event string) (spa1 []*SubscriptionWithWebhook, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetSubscriptionsWithWebhooksByEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"namespace": namespace,
				"event":     event}, map[string]interface{}{
				"spa1": spa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetSubscriptionsWithWebhooksByEvent(ctx, namespace, event)
}

// GetSubscriptionsByEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetSubscriptionsByEvent(ctx context.Context, namespace string, event string) (epa1 []*EventSubscription, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetSubscriptionsByEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"namespace": namespace,
				"event":     event}, map[string]interface{}{
				"epa1": epa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetSubscriptionsByEvent(ctx, namespace, event)
}

// GetWebhookByID implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetWebhookByID(ctx context.Context, webhookID uuid.UUID, namespace string) (wp1 *WebhookRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetWebhookByID")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"namespace": namespace}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetWebhookByID(ctx, webhookID, namespace)
}

// GetWebhookHealthState implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetWebhookHealthState(ctx context.Context, webhookID uuid.UUID) (wp1 *WebhookHealthMetrics, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetWebhookHealthState")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetWebhookHealthState(ctx, webhookID)
}

// GetWebhookHealthSummary implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetWebhookHealthSummary(ctx context.Context, webhookID uuid.UUID, hours int) (wp1 *WebhookHealthSummary, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetWebhookHealthSummary")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"hours":     hours}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetWebhookHealthSummary(ctx, webhookID, hours)
}

// GetWebhookHealthTimeSeries implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetWebhookHealthTimeSeries(ctx context.Context, webhookID uuid.UUID, hours int, bucketSize string) (wpa1 []*WebhookHealthEvent, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetWebhookHealthTimeSeries")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"webhookID":  webhookID,
				"hours":      hours,
				"bucketSize": bucketSize}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetWebhookHealthTimeSeries(ctx, webhookID, hours, bucketSize)
}

// GetWebhooksByHealth implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetWebhooksByHealth(ctx context.Context, health WebhookHealth) (wpa1 []*WebhookRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetWebhooksByHealth")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"health": health}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetWebhooksByHealth(ctx, health)
}

// GetWebhooksByNamespace implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) GetWebhooksByNamespace(ctx context.Context, namespace string, activeOnly bool) (wpa1 []*WebhookRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.GetWebhooksByNamespace")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"namespace":  namespace,
				"activeOnly": activeOnly}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.GetWebhooksByNamespace(ctx, namespace, activeOnly)
}

// ListEventReports implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) ListEventReports(ctx context.Context, namespace string, eventName *string, limit int, offset int) (epa1 []*EventReportWithStats, i1 int, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.ListEventReports")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"namespace": namespace,
				"eventName": eventName,
				"limit":     limit,
				"offset":    offset}, map[string]interface{}{
				"epa1": epa1,
				"i1":   i1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.ListEventReports(ctx, namespace, eventName, limit, offset)
}

// ListEventReportsWithStats implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) ListEventReportsWithStats(ctx context.Context, namespace string, eventName *string, limit int, offset int) (epa1 []*EventReportWithStats, i1 int, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.ListEventReportsWithStats")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"namespace": namespace,
				"eventName": eventName,
				"limit":     limit,
				"offset":    offset}, map[string]interface{}{
				"epa1": epa1,
				"i1":   i1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.ListEventReportsWithStats(ctx, namespace, eventName, limit, offset)
}

// ListEvents implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) ListEvents(ctx context.Context, activeOnly bool) (epa1 []*EventRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.ListEvents")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"activeOnly": activeOnly}, map[string]interface{}{
				"epa1": epa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.ListEvents(ctx, activeOnly)
}

// ListSubscriptions implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) ListSubscriptions(ctx context.Context, webhookID uuid.UUID) (epa1 []*EventSubscription, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.ListSubscriptions")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID}, map[string]interface{}{
				"epa1": epa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.ListSubscriptions(ctx, webhookID)
}

// ListWebhooks implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) ListWebhooks(ctx context.Context, namespace string, event string, activeOnly bool) (wpa1 []*WebhookRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.ListWebhooks")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"namespace":  namespace,
				"event":      event,
				"activeOnly": activeOnly}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.ListWebhooks(ctx, namespace, event, activeOnly)
}

// RecordWebhookHealthEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) RecordWebhookHealthEvent(ctx context.Context, webhookID uuid.UUID, deliveryID uuid.UUID, success bool, responseTime int, responseCode int, errorMessage string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.RecordWebhookHealthEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":          ctx,
				"webhookID":    webhookID,
				"deliveryID":   deliveryID,
				"success":      success,
				"responseTime": responseTime,
				"responseCode": responseCode,
				"errorMessage": errorMessage}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.RecordWebhookHealthEvent(ctx, webhookID, deliveryID, success, responseTime, responseCode, errorMessage)
}

// RegisterEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) RegisterEvent(ctx context.Context, event *EventRegistration) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.RegisterEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"event": event}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.RegisterEvent(ctx, event)
}

// RegisterWebhook implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) RegisterWebhook(ctx context.Context, registration *WebhookRegistration) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.RegisterWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":          ctx,
				"registration": registration}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.RegisterWebhook(ctx, registration)
}

// ResetDeliveryForRetry implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) ResetDeliveryForRetry(ctx context.Context, deliveryID uuid.UUID) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.ResetDeliveryForRetry")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"deliveryID": deliveryID}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.ResetDeliveryForRetry(ctx, deliveryID)
}

// StoreEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) StoreEvent(ctx context.Context, event *EventRecord) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.StoreEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"event": event}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.StoreEvent(ctx, event)
}

// UnregisterWebhook implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) UnregisterWebhook(ctx context.Context, webhookID uuid.UUID) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.UnregisterWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.UnregisterWebhook(ctx, webhookID)
}

// UpdateDeliveryRequestBody implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) UpdateDeliveryRequestBody(ctx context.Context, deliveryID uuid.UUID, requestBody string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.UpdateDeliveryRequestBody")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":         ctx,
				"deliveryID":  deliveryID,
				"requestBody": requestBody}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.UpdateDeliveryRequestBody(ctx, deliveryID, requestBody)
}

// UpdateDeliveryStatus implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) UpdateDeliveryStatus(ctx context.Context, deliveryID uuid.UUID, status WebhookDeliveryStatus, responseCode int, responseBody string, errorMessage string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.UpdateDeliveryStatus")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":          ctx,
				"deliveryID":   deliveryID,
				"status":       status,
				"responseCode": responseCode,
				"responseBody": responseBody,
				"errorMessage": errorMessage}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.UpdateDeliveryStatus(ctx, deliveryID, status, responseCode, responseBody, errorMessage)
}

// UpdateEvent implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) UpdateEvent(ctx context.Context, event *EventRegistration) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.UpdateEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":   ctx,
				"event": event}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.UpdateEvent(ctx, event)
}

// UpdateSubscription implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) UpdateSubscription(ctx context.Context, sub *EventSubscription) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.UpdateSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"sub": sub}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.UpdateSubscription(ctx, sub)
}

// UpdateWebhook implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) UpdateWebhook(ctx context.Context, webhook *WebhookRegistration) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.UpdateWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"webhook": webhook}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.UpdateWebhook(ctx, webhook)
}

// UpdateWebhookHealthState implements RepositoryInterface
func (_d RepositoryInterfaceWithTracing) UpdateWebhookHealthState(ctx context.Context, webhookID uuid.UUID, success bool, eventTimestamp time.Time) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "RepositoryInterface.UpdateWebhookHealthState")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"webhookID":      webhookID,
				"success":        success,
				"eventTimestamp": eventTimestamp}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.RepositoryInterface.UpdateWebhookHealthState(ctx, webhookID, success, eventTimestamp)
}
