{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sparrow.fullname" . }}-postgresql
  labels:
    {{- include "sparrow.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
