// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/webhook.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/sarathsp06/sparrow/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WebhookServiceName is the fully-qualified name of the WebhookService service.
	WebhookServiceName = "webhook.WebhookService"
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "webhook.EventService"
	// SubscriptionServiceName is the fully-qualified name of the SubscriptionService service.
	SubscriptionServiceName = "webhook.SubscriptionService"
	// DeliveryServiceName is the fully-qualified name of the DeliveryService service.
	DeliveryServiceName = "webhook.DeliveryService"
	// HealthServiceName is the fully-qualified name of the HealthService service.
	HealthServiceName = "webhook.HealthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WebhookServiceRegisterWebhookProcedure is the fully-qualified name of the WebhookService's
	// RegisterWebhook RPC.
	WebhookServiceRegisterWebhookProcedure = "/webhook.WebhookService/RegisterWebhook"
	// WebhookServiceUnregisterWebhookProcedure is the fully-qualified name of the WebhookService's
	// UnregisterWebhook RPC.
	WebhookServiceUnregisterWebhookProcedure = "/webhook.WebhookService/UnregisterWebhook"
	// WebhookServiceListWebhooksProcedure is the fully-qualified name of the WebhookService's
	// ListWebhooks RPC.
	WebhookServiceListWebhooksProcedure = "/webhook.WebhookService/ListWebhooks"
	// WebhookServiceUpdateWebhookConfigProcedure is the fully-qualified name of the WebhookService's
	// UpdateWebhookConfig RPC.
	WebhookServiceUpdateWebhookConfigProcedure = "/webhook.WebhookService/UpdateWebhookConfig"
	// WebhookServicePauseWebhookProcedure is the fully-qualified name of the WebhookService's
	// PauseWebhook RPC.
	WebhookServicePauseWebhookProcedure = "/webhook.WebhookService/PauseWebhook"
	// WebhookServiceResumeWebhookProcedure is the fully-qualified name of the WebhookService's
	// ResumeWebhook RPC.
	WebhookServiceResumeWebhookProcedure = "/webhook.WebhookService/ResumeWebhook"
	// WebhookServiceGetNamespaceStatsProcedure is the fully-qualified name of the WebhookService's
	// GetNamespaceStats RPC.
	WebhookServiceGetNamespaceStatsProcedure = "/webhook.WebhookService/GetNamespaceStats"
	// WebhookServiceGetTemplateFunctionsProcedure is the fully-qualified name of the WebhookService's
	// GetTemplateFunctions RPC.
	WebhookServiceGetTemplateFunctionsProcedure = "/webhook.WebhookService/GetTemplateFunctions"
	// EventServiceRegisterEventProcedure is the fully-qualified name of the EventService's
	// RegisterEvent RPC.
	EventServiceRegisterEventProcedure = "/webhook.EventService/RegisterEvent"
	// EventServiceListEventsProcedure is the fully-qualified name of the EventService's ListEvents RPC.
	EventServiceListEventsProcedure = "/webhook.EventService/ListEvents"
	// EventServiceUpdateEventProcedure is the fully-qualified name of the EventService's UpdateEvent
	// RPC.
	EventServiceUpdateEventProcedure = "/webhook.EventService/UpdateEvent"
	// EventServiceDeleteEventProcedure is the fully-qualified name of the EventService's DeleteEvent
	// RPC.
	EventServiceDeleteEventProcedure = "/webhook.EventService/DeleteEvent"
	// EventServiceGetEventProcedure is the fully-qualified name of the EventService's GetEvent RPC.
	EventServiceGetEventProcedure = "/webhook.EventService/GetEvent"
	// EventServicePushEventProcedure is the fully-qualified name of the EventService's PushEvent RPC.
	EventServicePushEventProcedure = "/webhook.EventService/PushEvent"
	// EventServiceListEventReportsProcedure is the fully-qualified name of the EventService's
	// ListEventReports RPC.
	EventServiceListEventReportsProcedure = "/webhook.EventService/ListEventReports"
	// SubscriptionServiceCreateSubscriptionProcedure is the fully-qualified name of the
	// SubscriptionService's CreateSubscription RPC.
	SubscriptionServiceCreateSubscriptionProcedure = "/webhook.SubscriptionService/CreateSubscription"
	// SubscriptionServiceGetSubscriptionProcedure is the fully-qualified name of the
	// SubscriptionService's GetSubscription RPC.
	SubscriptionServiceGetSubscriptionProcedure = "/webhook.SubscriptionService/GetSubscription"
	// SubscriptionServiceListSubscriptionsProcedure is the fully-qualified name of the
	// SubscriptionService's ListSubscriptions RPC.
	SubscriptionServiceListSubscriptionsProcedure = "/webhook.SubscriptionService/ListSubscriptions"
	// SubscriptionServiceUpdateSubscriptionProcedure is the fully-qualified name of the
	// SubscriptionService's UpdateSubscription RPC.
	SubscriptionServiceUpdateSubscriptionProcedure = "/webhook.SubscriptionService/UpdateSubscription"
	// SubscriptionServiceDeleteSubscriptionProcedure is the fully-qualified name of the
	// SubscriptionService's DeleteSubscription RPC.
	SubscriptionServiceDeleteSubscriptionProcedure = "/webhook.SubscriptionService/DeleteSubscription"
	// SubscriptionServiceTestSubscriptionTemplateProcedure is the fully-qualified name of the
	// SubscriptionService's TestSubscriptionTemplate RPC.
	SubscriptionServiceTestSubscriptionTemplateProcedure = "/webhook.SubscriptionService/TestSubscriptionTemplate"
	// DeliveryServiceGetDeliveryStatusProcedure is the fully-qualified name of the DeliveryService's
	// GetDeliveryStatus RPC.
	DeliveryServiceGetDeliveryStatusProcedure = "/webhook.DeliveryService/GetDeliveryStatus"
	// DeliveryServiceListDeliveriesProcedure is the fully-qualified name of the DeliveryService's
	// ListDeliveries RPC.
	DeliveryServiceListDeliveriesProcedure = "/webhook.DeliveryService/ListDeliveries"
	// DeliveryServiceRetryDeliveryProcedure is the fully-qualified name of the DeliveryService's
	// RetryDelivery RPC.
	DeliveryServiceRetryDeliveryProcedure = "/webhook.DeliveryService/RetryDelivery"
	// DeliveryServiceGetDeliveryAttemptsProcedure is the fully-qualified name of the DeliveryService's
	// GetDeliveryAttempts RPC.
	DeliveryServiceGetDeliveryAttemptsProcedure = "/webhook.DeliveryService/GetDeliveryAttempts"
	// HealthServiceGetWebhookHealthProcedure is the fully-qualified name of the HealthService's
	// GetWebhookHealth RPC.
	HealthServiceGetWebhookHealthProcedure = "/webhook.HealthService/GetWebhookHealth"
	// HealthServiceListWebhooksByHealthProcedure is the fully-qualified name of the HealthService's
	// ListWebhooksByHealth RPC.
	HealthServiceListWebhooksByHealthProcedure = "/webhook.HealthService/ListWebhooksByHealth"
	// HealthServiceGetHealthSummaryProcedure is the fully-qualified name of the HealthService's
	// GetHealthSummary RPC.
	HealthServiceGetHealthSummaryProcedure = "/webhook.HealthService/GetHealthSummary"
)

// WebhookServiceClient is a client for the webhook.WebhookService service.
type WebhookServiceClient interface {
	// RegisterWebhook registers a URL for specific events in a namespace
	RegisterWebhook(context.Context, *connect.Request[proto.RegisterWebhookRequest]) (*connect.Response[proto.RegisterWebhookResponse], error)
	// UnregisterWebhook removes a webhook registration
	UnregisterWebhook(context.Context, *connect.Request[proto.UnregisterWebhookRequest]) (*connect.Response[proto.UnregisterWebhookResponse], error)
	// ListWebhooks lists all registered webhooks for a namespace with filters
	ListWebhooks(context.Context, *connect.Request[proto.ListWebhooksRequest]) (*connect.Response[proto.ListWebhooksResponse], error)
	// UpdateWebhookConfig updates webhook configuration
	UpdateWebhookConfig(context.Context, *connect.Request[proto.UpdateWebhookConfigRequest]) (*connect.Response[proto.UpdateWebhookConfigResponse], error)
	// PauseWebhook temporarily disables a webhook
	PauseWebhook(context.Context, *connect.Request[proto.PauseWebhookRequest]) (*connect.Response[proto.PauseWebhookResponse], error)
	// ResumeWebhook re-enables a paused webhook
	ResumeWebhook(context.Context, *connect.Request[proto.ResumeWebhookRequest]) (*connect.Response[proto.ResumeWebhookResponse], error)
	// GetNamespaceStats retrieves statistics for a namespace
	GetNamespaceStats(context.Context, *connect.Request[proto.GetNamespaceStatsRequest]) (*connect.Response[proto.GetNamespaceStatsResponse], error)
	// GetTemplateFunctions returns all available template functions with their descriptions
	GetTemplateFunctions(context.Context, *connect.Request[proto.GetTemplateFunctionsRequest]) (*connect.Response[proto.GetTemplateFunctionsResponse], error)
}

// NewWebhookServiceClient constructs a client for the webhook.WebhookService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWebhookServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WebhookServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	webhookServiceMethods := proto.File_proto_webhook_proto.Services().ByName("WebhookService").Methods()
	return &webhookServiceClient{
		registerWebhook: connect.NewClient[proto.RegisterWebhookRequest, proto.RegisterWebhookResponse](
			httpClient,
			baseURL+WebhookServiceRegisterWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("RegisterWebhook")),
			connect.WithClientOptions(opts...),
		),
		unregisterWebhook: connect.NewClient[proto.UnregisterWebhookRequest, proto.UnregisterWebhookResponse](
			httpClient,
			baseURL+WebhookServiceUnregisterWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("UnregisterWebhook")),
			connect.WithClientOptions(opts...),
		),
		listWebhooks: connect.NewClient[proto.ListWebhooksRequest, proto.ListWebhooksResponse](
			httpClient,
			baseURL+WebhookServiceListWebhooksProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("ListWebhooks")),
			connect.WithClientOptions(opts...),
		),
		updateWebhookConfig: connect.NewClient[proto.UpdateWebhookConfigRequest, proto.UpdateWebhookConfigResponse](
			httpClient,
			baseURL+WebhookServiceUpdateWebhookConfigProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("UpdateWebhookConfig")),
			connect.WithClientOptions(opts...),
		),
		pauseWebhook: connect.NewClient[proto.PauseWebhookRequest, proto.PauseWebhookResponse](
			httpClient,
			baseURL+WebhookServicePauseWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("PauseWebhook")),
			connect.WithClientOptions(opts...),
		),
		resumeWebhook: connect.NewClient[proto.ResumeWebhookRequest, proto.ResumeWebhookResponse](
			httpClient,
			baseURL+WebhookServiceResumeWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("ResumeWebhook")),
			connect.WithClientOptions(opts...),
		),
		getNamespaceStats: connect.NewClient[proto.GetNamespaceStatsRequest, proto.GetNamespaceStatsResponse](
			httpClient,
			baseURL+WebhookServiceGetNamespaceStatsProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("GetNamespaceStats")),
			connect.WithClientOptions(opts...),
		),
		getTemplateFunctions: connect.NewClient[proto.GetTemplateFunctionsRequest, proto.GetTemplateFunctionsResponse](
			httpClient,
			baseURL+WebhookServiceGetTemplateFunctionsProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("GetTemplateFunctions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// webhookServiceClient implements WebhookServiceClient.
type webhookServiceClient struct {
	registerWebhook      *connect.Client[proto.RegisterWebhookRequest, proto.RegisterWebhookResponse]
	unregisterWebhook    *connect.Client[proto.UnregisterWebhookRequest, proto.UnregisterWebhookResponse]
	listWebhooks         *connect.Client[proto.ListWebhooksRequest, proto.ListWebhooksResponse]
	updateWebhookConfig  *connect.Client[proto.UpdateWebhookConfigRequest, proto.UpdateWebhookConfigResponse]
	pauseWebhook         *connect.Client[proto.PauseWebhookRequest, proto.PauseWebhookResponse]
	resumeWebhook        *connect.Client[proto.ResumeWebhookRequest, proto.ResumeWebhookResponse]
	getNamespaceStats    *connect.Client[proto.GetNamespaceStatsRequest, proto.GetNamespaceStatsResponse]
	getTemplateFunctions *connect.Client[proto.GetTemplateFunctionsRequest, proto.GetTemplateFunctionsResponse]
}

// RegisterWebhook calls webhook.WebhookService.RegisterWebhook.
func (c *webhookServiceClient) RegisterWebhook(ctx context.Context, req *connect.Request[proto.RegisterWebhookRequest]) (*connect.Response[proto.RegisterWebhookResponse], error) {
	return c.registerWebhook.CallUnary(ctx, req)
}

// UnregisterWebhook calls webhook.WebhookService.UnregisterWebhook.
func (c *webhookServiceClient) UnregisterWebhook(ctx context.Context, req *connect.Request[proto.UnregisterWebhookRequest]) (*connect.Response[proto.UnregisterWebhookResponse], error) {
	return c.unregisterWebhook.CallUnary(ctx, req)
}

// ListWebhooks calls webhook.WebhookService.ListWebhooks.
func (c *webhookServiceClient) ListWebhooks(ctx context.Context, req *connect.Request[proto.ListWebhooksRequest]) (*connect.Response[proto.ListWebhooksResponse], error) {
	return c.listWebhooks.CallUnary(ctx, req)
}

// UpdateWebhookConfig calls webhook.WebhookService.UpdateWebhookConfig.
func (c *webhookServiceClient) UpdateWebhookConfig(ctx context.Context, req *connect.Request[proto.UpdateWebhookConfigRequest]) (*connect.Response[proto.UpdateWebhookConfigResponse], error) {
	return c.updateWebhookConfig.CallUnary(ctx, req)
}

// PauseWebhook calls webhook.WebhookService.PauseWebhook.
func (c *webhookServiceClient) PauseWebhook(ctx context.Context, req *connect.Request[proto.PauseWebhookRequest]) (*connect.Response[proto.PauseWebhookResponse], error) {
	return c.pauseWebhook.CallUnary(ctx, req)
}

// ResumeWebhook calls webhook.WebhookService.ResumeWebhook.
func (c *webhookServiceClient) ResumeWebhook(ctx context.Context, req *connect.Request[proto.ResumeWebhookRequest]) (*connect.Response[proto.ResumeWebhookResponse], error) {
	return c.resumeWebhook.CallUnary(ctx, req)
}

// GetNamespaceStats calls webhook.WebhookService.GetNamespaceStats.
func (c *webhookServiceClient) GetNamespaceStats(ctx context.Context, req *connect.Request[proto.GetNamespaceStatsRequest]) (*connect.Response[proto.GetNamespaceStatsResponse], error) {
	return c.getNamespaceStats.CallUnary(ctx, req)
}

// GetTemplateFunctions calls webhook.WebhookService.GetTemplateFunctions.
func (c *webhookServiceClient) GetTemplateFunctions(ctx context.Context, req *connect.Request[proto.GetTemplateFunctionsRequest]) (*connect.Response[proto.GetTemplateFunctionsResponse], error) {
	return c.getTemplateFunctions.CallUnary(ctx, req)
}

// WebhookServiceHandler is an implementation of the webhook.WebhookService service.
type WebhookServiceHandler interface {
	// RegisterWebhook registers a URL for specific events in a namespace
	RegisterWebhook(context.Context, *connect.Request[proto.RegisterWebhookRequest]) (*connect.Response[proto.RegisterWebhookResponse], error)
	// UnregisterWebhook removes a webhook registration
	UnregisterWebhook(context.Context, *connect.Request[proto.UnregisterWebhookRequest]) (*connect.Response[proto.UnregisterWebhookResponse], error)
	// ListWebhooks lists all registered webhooks for a namespace with filters
	ListWebhooks(context.Context, *connect.Request[proto.ListWebhooksRequest]) (*connect.Response[proto.ListWebhooksResponse], error)
	// UpdateWebhookConfig updates webhook configuration
	UpdateWebhookConfig(context.Context, *connect.Request[proto.UpdateWebhookConfigRequest]) (*connect.Response[proto.UpdateWebhookConfigResponse], error)
	// PauseWebhook temporarily disables a webhook
	PauseWebhook(context.Context, *connect.Request[proto.PauseWebhookRequest]) (*connect.Response[proto.PauseWebhookResponse], error)
	// ResumeWebhook re-enables a paused webhook
	ResumeWebhook(context.Context, *connect.Request[proto.ResumeWebhookRequest]) (*connect.Response[proto.ResumeWebhookResponse], error)
	// GetNamespaceStats retrieves statistics for a namespace
	GetNamespaceStats(context.Context, *connect.Request[proto.GetNamespaceStatsRequest]) (*connect.Response[proto.GetNamespaceStatsResponse], error)
	// GetTemplateFunctions returns all available template functions with their descriptions
	GetTemplateFunctions(context.Context, *connect.Request[proto.GetTemplateFunctionsRequest]) (*connect.Response[proto.GetTemplateFunctionsResponse], error)
}

// NewWebhookServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWebhookServiceHandler(svc WebhookServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	webhookServiceMethods := proto.File_proto_webhook_proto.Services().ByName("WebhookService").Methods()
	webhookServiceRegisterWebhookHandler := connect.NewUnaryHandler(
		WebhookServiceRegisterWebhookProcedure,
		svc.RegisterWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("RegisterWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceUnregisterWebhookHandler := connect.NewUnaryHandler(
		WebhookServiceUnregisterWebhookProcedure,
		svc.UnregisterWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("UnregisterWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceListWebhooksHandler := connect.NewUnaryHandler(
		WebhookServiceListWebhooksProcedure,
		svc.ListWebhooks,
		connect.WithSchema(webhookServiceMethods.ByName("ListWebhooks")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceUpdateWebhookConfigHandler := connect.NewUnaryHandler(
		WebhookServiceUpdateWebhookConfigProcedure,
		svc.UpdateWebhookConfig,
		connect.WithSchema(webhookServiceMethods.ByName("UpdateWebhookConfig")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServicePauseWebhookHandler := connect.NewUnaryHandler(
		WebhookServicePauseWebhookProcedure,
		svc.PauseWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("PauseWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceResumeWebhookHandler := connect.NewUnaryHandler(
		WebhookServiceResumeWebhookProcedure,
		svc.ResumeWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("ResumeWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceGetNamespaceStatsHandler := connect.NewUnaryHandler(
		WebhookServiceGetNamespaceStatsProcedure,
		svc.GetNamespaceStats,
		connect.WithSchema(webhookServiceMethods.ByName("GetNamespaceStats")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceGetTemplateFunctionsHandler := connect.NewUnaryHandler(
		WebhookServiceGetTemplateFunctionsProcedure,
		svc.GetTemplateFunctions,
		connect.WithSchema(webhookServiceMethods.ByName("GetTemplateFunctions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/webhook.WebhookService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WebhookServiceRegisterWebhookProcedure:
			webhookServiceRegisterWebhookHandler.ServeHTTP(w, r)
		case WebhookServiceUnregisterWebhookProcedure:
			webhookServiceUnregisterWebhookHandler.ServeHTTP(w, r)
		case WebhookServiceListWebhooksProcedure:
			webhookServiceListWebhooksHandler.ServeHTTP(w, r)
		case WebhookServiceUpdateWebhookConfigProcedure:
			webhookServiceUpdateWebhookConfigHandler.ServeHTTP(w, r)
		case WebhookServicePauseWebhookProcedure:
			webhookServicePauseWebhookHandler.ServeHTTP(w, r)
		case WebhookServiceResumeWebhookProcedure:
			webhookServiceResumeWebhookHandler.ServeHTTP(w, r)
		case WebhookServiceGetNamespaceStatsProcedure:
			webhookServiceGetNamespaceStatsHandler.ServeHTTP(w, r)
		case WebhookServiceGetTemplateFunctionsProcedure:
			webhookServiceGetTemplateFunctionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWebhookServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWebhookServiceHandler struct{}

func (UnimplementedWebhookServiceHandler) RegisterWebhook(context.Context, *connect.Request[proto.RegisterWebhookRequest]) (*connect.Response[proto.RegisterWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.RegisterWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) UnregisterWebhook(context.Context, *connect.Request[proto.UnregisterWebhookRequest]) (*connect.Response[proto.UnregisterWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.UnregisterWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) ListWebhooks(context.Context, *connect.Request[proto.ListWebhooksRequest]) (*connect.Response[proto.ListWebhooksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.ListWebhooks is not implemented"))
}

func (UnimplementedWebhookServiceHandler) UpdateWebhookConfig(context.Context, *connect.Request[proto.UpdateWebhookConfigRequest]) (*connect.Response[proto.UpdateWebhookConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.UpdateWebhookConfig is not implemented"))
}

func (UnimplementedWebhookServiceHandler) PauseWebhook(context.Context, *connect.Request[proto.PauseWebhookRequest]) (*connect.Response[proto.PauseWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.PauseWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) ResumeWebhook(context.Context, *connect.Request[proto.ResumeWebhookRequest]) (*connect.Response[proto.ResumeWebhookResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.ResumeWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) GetNamespaceStats(context.Context, *connect.Request[proto.GetNamespaceStatsRequest]) (*connect.Response[proto.GetNamespaceStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.GetNamespaceStats is not implemented"))
}

func (UnimplementedWebhookServiceHandler) GetTemplateFunctions(context.Context, *connect.Request[proto.GetTemplateFunctionsRequest]) (*connect.Response[proto.GetTemplateFunctionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.WebhookService.GetTemplateFunctions is not implemented"))
}

// EventServiceClient is a client for the webhook.EventService service.
type EventServiceClient interface {
	// RegisterEvent registers a new event type
	RegisterEvent(context.Context, *connect.Request[proto.RegisterEventRequest]) (*connect.Response[proto.RegisterEventResponse], error)
	// ListEvents lists all registered event types
	ListEvents(context.Context, *connect.Request[proto.ListEventsRequest]) (*connect.Response[proto.ListEventsResponse], error)
	// UpdateEvent updates an event registration
	UpdateEvent(context.Context, *connect.Request[proto.UpdateEventRequest]) (*connect.Response[proto.UpdateEventResponse], error)
	// DeleteEvent deletes an event registration
	DeleteEvent(context.Context, *connect.Request[proto.DeleteEventRequest]) (*connect.Response[proto.DeleteEventResponse], error)
	// GetEvent retrieves an event type by name
	GetEvent(context.Context, *connect.Request[proto.GetEventRequest]) (*connect.Response[proto.GetEventResponse], error)
	// PushEvent pushes an event that triggers registered webhooks
	PushEvent(context.Context, *connect.Request[proto.PushEventRequest]) (*connect.Response[proto.PushEventResponse], error)
	// ListEventReports lists all events in descending order for a given namespace
	ListEventReports(context.Context, *connect.Request[proto.ListEventReportsRequest]) (*connect.Response[proto.ListEventReportsResponse], error)
}

// NewEventServiceClient constructs a client for the webhook.EventService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := proto.File_proto_webhook_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		registerEvent: connect.NewClient[proto.RegisterEventRequest, proto.RegisterEventResponse](
			httpClient,
			baseURL+EventServiceRegisterEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("RegisterEvent")),
			connect.WithClientOptions(opts...),
		),
		listEvents: connect.NewClient[proto.ListEventsRequest, proto.ListEventsResponse](
			httpClient,
			baseURL+EventServiceListEventsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
			connect.WithClientOptions(opts...),
		),
		updateEvent: connect.NewClient[proto.UpdateEventRequest, proto.UpdateEventResponse](
			httpClient,
			baseURL+EventServiceUpdateEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("UpdateEvent")),
			connect.WithClientOptions(opts...),
		),
		deleteEvent: connect.NewClient[proto.DeleteEventRequest, proto.DeleteEventResponse](
			httpClient,
			baseURL+EventServiceDeleteEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("DeleteEvent")),
			connect.WithClientOptions(opts...),
		),
		getEvent: connect.NewClient[proto.GetEventRequest, proto.GetEventResponse](
			httpClient,
			baseURL+EventServiceGetEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
			connect.WithClientOptions(opts...),
		),
		pushEvent: connect.NewClient[proto.PushEventRequest, proto.PushEventResponse](
			httpClient,
			baseURL+EventServicePushEventProcedure,
			connect.WithSchema(eventServiceMethods.ByName("PushEvent")),
			connect.WithClientOptions(opts...),
		),
		listEventReports: connect.NewClient[proto.ListEventReportsRequest, proto.ListEventReportsResponse](
			httpClient,
			baseURL+EventServiceListEventReportsProcedure,
			connect.WithSchema(eventServiceMethods.ByName("ListEventReports")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	registerEvent    *connect.Client[proto.RegisterEventRequest, proto.RegisterEventResponse]
	listEvents       *connect.Client[proto.ListEventsRequest, proto.ListEventsResponse]
	updateEvent      *connect.Client[proto.UpdateEventRequest, proto.UpdateEventResponse]
	deleteEvent      *connect.Client[proto.DeleteEventRequest, proto.DeleteEventResponse]
	getEvent         *connect.Client[proto.GetEventRequest, proto.GetEventResponse]
	pushEvent        *connect.Client[proto.PushEventRequest, proto.PushEventResponse]
	listEventReports *connect.Client[proto.ListEventReportsRequest, proto.ListEventReportsResponse]
}

// RegisterEvent calls webhook.EventService.RegisterEvent.
func (c *eventServiceClient) RegisterEvent(ctx context.Context, req *connect.Request[proto.RegisterEventRequest]) (*connect.Response[proto.RegisterEventResponse], error) {
	return c.registerEvent.CallUnary(ctx, req)
}

// ListEvents calls webhook.EventService.ListEvents.
func (c *eventServiceClient) ListEvents(ctx context.Context, req *connect.Request[proto.ListEventsRequest]) (*connect.Response[proto.ListEventsResponse], error) {
	return c.listEvents.CallUnary(ctx, req)
}

// UpdateEvent calls webhook.EventService.UpdateEvent.
func (c *eventServiceClient) UpdateEvent(ctx context.Context, req *connect.Request[proto.UpdateEventRequest]) (*connect.Response[proto.UpdateEventResponse], error) {
	return c.updateEvent.CallUnary(ctx, req)
}

// DeleteEvent calls webhook.EventService.DeleteEvent.
func (c *eventServiceClient) DeleteEvent(ctx context.Context, req *connect.Request[proto.DeleteEventRequest]) (*connect.Response[proto.DeleteEventResponse], error) {
	return c.deleteEvent.CallUnary(ctx, req)
}

// GetEvent calls webhook.EventService.GetEvent.
func (c *eventServiceClient) GetEvent(ctx context.Context, req *connect.Request[proto.GetEventRequest]) (*connect.Response[proto.GetEventResponse], error) {
	return c.getEvent.CallUnary(ctx, req)
}

// PushEvent calls webhook.EventService.PushEvent.
func (c *eventServiceClient) PushEvent(ctx context.Context, req *connect.Request[proto.PushEventRequest]) (*connect.Response[proto.PushEventResponse], error) {
	return c.pushEvent.CallUnary(ctx, req)
}

// ListEventReports calls webhook.EventService.ListEventReports.
func (c *eventServiceClient) ListEventReports(ctx context.Context, req *connect.Request[proto.ListEventReportsRequest]) (*connect.Response[proto.ListEventReportsResponse], error) {
	return c.listEventReports.CallUnary(ctx, req)
}

// EventServiceHandler is an implementation of the webhook.EventService service.
type EventServiceHandler interface {
	// RegisterEvent registers a new event type
	RegisterEvent(context.Context, *connect.Request[proto.RegisterEventRequest]) (*connect.Response[proto.RegisterEventResponse], error)
	// ListEvents lists all registered event types
	ListEvents(context.Context, *connect.Request[proto.ListEventsRequest]) (*connect.Response[proto.ListEventsResponse], error)
	// UpdateEvent updates an event registration
	UpdateEvent(context.Context, *connect.Request[proto.UpdateEventRequest]) (*connect.Response[proto.UpdateEventResponse], error)
	// DeleteEvent deletes an event registration
	DeleteEvent(context.Context, *connect.Request[proto.DeleteEventRequest]) (*connect.Response[proto.DeleteEventResponse], error)
	// GetEvent retrieves an event type by name
	GetEvent(context.Context, *connect.Request[proto.GetEventRequest]) (*connect.Response[proto.GetEventResponse], error)
	// PushEvent pushes an event that triggers registered webhooks
	PushEvent(context.Context, *connect.Request[proto.PushEventRequest]) (*connect.Response[proto.PushEventResponse], error)
	// ListEventReports lists all events in descending order for a given namespace
	ListEventReports(context.Context, *connect.Request[proto.ListEventReportsRequest]) (*connect.Response[proto.ListEventReportsResponse], error)
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := proto.File_proto_webhook_proto.Services().ByName("EventService").Methods()
	eventServiceRegisterEventHandler := connect.NewUnaryHandler(
		EventServiceRegisterEventProcedure,
		svc.RegisterEvent,
		connect.WithSchema(eventServiceMethods.ByName("RegisterEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListEventsHandler := connect.NewUnaryHandler(
		EventServiceListEventsProcedure,
		svc.ListEvents,
		connect.WithSchema(eventServiceMethods.ByName("ListEvents")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceUpdateEventHandler := connect.NewUnaryHandler(
		EventServiceUpdateEventProcedure,
		svc.UpdateEvent,
		connect.WithSchema(eventServiceMethods.ByName("UpdateEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceDeleteEventHandler := connect.NewUnaryHandler(
		EventServiceDeleteEventProcedure,
		svc.DeleteEvent,
		connect.WithSchema(eventServiceMethods.ByName("DeleteEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceGetEventHandler := connect.NewUnaryHandler(
		EventServiceGetEventProcedure,
		svc.GetEvent,
		connect.WithSchema(eventServiceMethods.ByName("GetEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServicePushEventHandler := connect.NewUnaryHandler(
		EventServicePushEventProcedure,
		svc.PushEvent,
		connect.WithSchema(eventServiceMethods.ByName("PushEvent")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceListEventReportsHandler := connect.NewUnaryHandler(
		EventServiceListEventReportsProcedure,
		svc.ListEventReports,
		connect.WithSchema(eventServiceMethods.ByName("ListEventReports")),
		connect.WithHandlerOptions(opts...),
	)
	return "/webhook.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServiceRegisterEventProcedure:
			eventServiceRegisterEventHandler.ServeHTTP(w, r)
		case EventServiceListEventsProcedure:
			eventServiceListEventsHandler.ServeHTTP(w, r)
		case EventServiceUpdateEventProcedure:
			eventServiceUpdateEventHandler.ServeHTTP(w, r)
		case EventServiceDeleteEventProcedure:
			eventServiceDeleteEventHandler.ServeHTTP(w, r)
		case EventServiceGetEventProcedure:
			eventServiceGetEventHandler.ServeHTTP(w, r)
		case EventServicePushEventProcedure:
			eventServicePushEventHandler.ServeHTTP(w, r)
		case EventServiceListEventReportsProcedure:
			eventServiceListEventReportsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) RegisterEvent(context.Context, *connect.Request[proto.RegisterEventRequest]) (*connect.Response[proto.RegisterEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.EventService.RegisterEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) ListEvents(context.Context, *connect.Request[proto.ListEventsRequest]) (*connect.Response[proto.ListEventsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.EventService.ListEvents is not implemented"))
}

func (UnimplementedEventServiceHandler) UpdateEvent(context.Context, *connect.Request[proto.UpdateEventRequest]) (*connect.Response[proto.UpdateEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.EventService.UpdateEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) DeleteEvent(context.Context, *connect.Request[proto.DeleteEventRequest]) (*connect.Response[proto.DeleteEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.EventService.DeleteEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) GetEvent(context.Context, *connect.Request[proto.GetEventRequest]) (*connect.Response[proto.GetEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.EventService.GetEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) PushEvent(context.Context, *connect.Request[proto.PushEventRequest]) (*connect.Response[proto.PushEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.EventService.PushEvent is not implemented"))
}

func (UnimplementedEventServiceHandler) ListEventReports(context.Context, *connect.Request[proto.ListEventReportsRequest]) (*connect.Response[proto.ListEventReportsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.EventService.ListEventReports is not implemented"))
}

// SubscriptionServiceClient is a client for the webhook.SubscriptionService service.
type SubscriptionServiceClient interface {
	// CreateSubscription creates a new event subscription for a webhook
	CreateSubscription(context.Context, *connect.Request[proto.CreateSubscriptionRequest]) (*connect.Response[proto.CreateSubscriptionResponse], error)
	// GetSubscription retrieves a specific subscription by ID
	GetSubscription(context.Context, *connect.Request[proto.GetSubscriptionRequest]) (*connect.Response[proto.GetSubscriptionResponse], error)
	// ListSubscriptions lists all subscriptions for a webhook or event
	ListSubscriptions(context.Context, *connect.Request[proto.ListSubscriptionsRequest]) (*connect.Response[proto.ListSubscriptionsResponse], error)
	// UpdateSubscription updates an existing subscription
	UpdateSubscription(context.Context, *connect.Request[proto.UpdateSubscriptionRequest]) (*connect.Response[proto.UpdateSubscriptionResponse], error)
	// DeleteSubscription deletes a subscription
	DeleteSubscription(context.Context, *connect.Request[proto.DeleteSubscriptionRequest]) (*connect.Response[proto.DeleteSubscriptionResponse], error)
	// TestSubscriptionTemplate dry-runs a transformation template with sample data
	TestSubscriptionTemplate(context.Context, *connect.Request[proto.TestSubscriptionTemplateRequest]) (*connect.Response[proto.TestSubscriptionTemplateResponse], error)
}

// NewSubscriptionServiceClient constructs a client for the webhook.SubscriptionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSubscriptionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SubscriptionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	subscriptionServiceMethods := proto.File_proto_webhook_proto.Services().ByName("SubscriptionService").Methods()
	return &subscriptionServiceClient{
		createSubscription: connect.NewClient[proto.CreateSubscriptionRequest, proto.CreateSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionServiceCreateSubscriptionProcedure,
			connect.WithSchema(subscriptionServiceMethods.ByName("CreateSubscription")),
			connect.WithClientOptions(opts...),
		),
		getSubscription: connect.NewClient[proto.GetSubscriptionRequest, proto.GetSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionServiceGetSubscriptionProcedure,
			connect.WithSchema(subscriptionServiceMethods.ByName("GetSubscription")),
			connect.WithClientOptions(opts...),
		),
		listSubscriptions: connect.NewClient[proto.ListSubscriptionsRequest, proto.ListSubscriptionsResponse](
			httpClient,
			baseURL+SubscriptionServiceListSubscriptionsProcedure,
			connect.WithSchema(subscriptionServiceMethods.ByName("ListSubscriptions")),
			connect.WithClientOptions(opts...),
		),
		updateSubscription: connect.NewClient[proto.UpdateSubscriptionRequest, proto.UpdateSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionServiceUpdateSubscriptionProcedure,
			connect.WithSchema(subscriptionServiceMethods.ByName("UpdateSubscription")),
			connect.WithClientOptions(opts...),
		),
		deleteSubscription: connect.NewClient[proto.DeleteSubscriptionRequest, proto.DeleteSubscriptionResponse](
			httpClient,
			baseURL+SubscriptionServiceDeleteSubscriptionProcedure,
			connect.WithSchema(subscriptionServiceMethods.ByName("DeleteSubscription")),
			connect.WithClientOptions(opts...),
		),
		testSubscriptionTemplate: connect.NewClient[proto.TestSubscriptionTemplateRequest, proto.TestSubscriptionTemplateResponse](
			httpClient,
			baseURL+SubscriptionServiceTestSubscriptionTemplateProcedure,
			connect.WithSchema(subscriptionServiceMethods.ByName("TestSubscriptionTemplate")),
			connect.WithClientOptions(opts...),
		),
	}
}

// subscriptionServiceClient implements SubscriptionServiceClient.
type subscriptionServiceClient struct {
	createSubscription       *connect.Client[proto.CreateSubscriptionRequest, proto.CreateSubscriptionResponse]
	getSubscription          *connect.Client[proto.GetSubscriptionRequest, proto.GetSubscriptionResponse]
	listSubscriptions        *connect.Client[proto.ListSubscriptionsRequest, proto.ListSubscriptionsResponse]
	updateSubscription       *connect.Client[proto.UpdateSubscriptionRequest, proto.UpdateSubscriptionResponse]
	deleteSubscription       *connect.Client[proto.DeleteSubscriptionRequest, proto.DeleteSubscriptionResponse]
	testSubscriptionTemplate *connect.Client[proto.TestSubscriptionTemplateRequest, proto.TestSubscriptionTemplateResponse]
}

// CreateSubscription calls webhook.SubscriptionService.CreateSubscription.
func (c *subscriptionServiceClient) CreateSubscription(ctx context.Context, req *connect.Request[proto.CreateSubscriptionRequest]) (*connect.Response[proto.CreateSubscriptionResponse], error) {
	return c.createSubscription.CallUnary(ctx, req)
}

// GetSubscription calls webhook.SubscriptionService.GetSubscription.
func (c *subscriptionServiceClient) GetSubscription(ctx context.Context, req *connect.Request[proto.GetSubscriptionRequest]) (*connect.Response[proto.GetSubscriptionResponse], error) {
	return c.getSubscription.CallUnary(ctx, req)
}

// ListSubscriptions calls webhook.SubscriptionService.ListSubscriptions.
func (c *subscriptionServiceClient) ListSubscriptions(ctx context.Context, req *connect.Request[proto.ListSubscriptionsRequest]) (*connect.Response[proto.ListSubscriptionsResponse], error) {
	return c.listSubscriptions.CallUnary(ctx, req)
}

// UpdateSubscription calls webhook.SubscriptionService.UpdateSubscription.
func (c *subscriptionServiceClient) UpdateSubscription(ctx context.Context, req *connect.Request[proto.UpdateSubscriptionRequest]) (*connect.Response[proto.UpdateSubscriptionResponse], error) {
	return c.updateSubscription.CallUnary(ctx, req)
}

// DeleteSubscription calls webhook.SubscriptionService.DeleteSubscription.
func (c *subscriptionServiceClient) DeleteSubscription(ctx context.Context, req *connect.Request[proto.DeleteSubscriptionRequest]) (*connect.Response[proto.DeleteSubscriptionResponse], error) {
	return c.deleteSubscription.CallUnary(ctx, req)
}

// TestSubscriptionTemplate calls webhook.SubscriptionService.TestSubscriptionTemplate.
func (c *subscriptionServiceClient) TestSubscriptionTemplate(ctx context.Context, req *connect.Request[proto.TestSubscriptionTemplateRequest]) (*connect.Response[proto.TestSubscriptionTemplateResponse], error) {
	return c.testSubscriptionTemplate.CallUnary(ctx, req)
}

// SubscriptionServiceHandler is an implementation of the webhook.SubscriptionService service.
type SubscriptionServiceHandler interface {
	// CreateSubscription creates a new event subscription for a webhook
	CreateSubscription(context.Context, *connect.Request[proto.CreateSubscriptionRequest]) (*connect.Response[proto.CreateSubscriptionResponse], error)
	// GetSubscription retrieves a specific subscription by ID
	GetSubscription(context.Context, *connect.Request[proto.GetSubscriptionRequest]) (*connect.Response[proto.GetSubscriptionResponse], error)
	// ListSubscriptions lists all subscriptions for a webhook or event
	ListSubscriptions(context.Context, *connect.Request[proto.ListSubscriptionsRequest]) (*connect.Response[proto.ListSubscriptionsResponse], error)
	// UpdateSubscription updates an existing subscription
	UpdateSubscription(context.Context, *connect.Request[proto.UpdateSubscriptionRequest]) (*connect.Response[proto.UpdateSubscriptionResponse], error)
	// DeleteSubscription deletes a subscription
	DeleteSubscription(context.Context, *connect.Request[proto.DeleteSubscriptionRequest]) (*connect.Response[proto.DeleteSubscriptionResponse], error)
	// TestSubscriptionTemplate dry-runs a transformation template with sample data
	TestSubscriptionTemplate(context.Context, *connect.Request[proto.TestSubscriptionTemplateRequest]) (*connect.Response[proto.TestSubscriptionTemplateResponse], error)
}

// NewSubscriptionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSubscriptionServiceHandler(svc SubscriptionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	subscriptionServiceMethods := proto.File_proto_webhook_proto.Services().ByName("SubscriptionService").Methods()
	subscriptionServiceCreateSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionServiceCreateSubscriptionProcedure,
		svc.CreateSubscription,
		connect.WithSchema(subscriptionServiceMethods.ByName("CreateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionServiceGetSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionServiceGetSubscriptionProcedure,
		svc.GetSubscription,
		connect.WithSchema(subscriptionServiceMethods.ByName("GetSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionServiceListSubscriptionsHandler := connect.NewUnaryHandler(
		SubscriptionServiceListSubscriptionsProcedure,
		svc.ListSubscriptions,
		connect.WithSchema(subscriptionServiceMethods.ByName("ListSubscriptions")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionServiceUpdateSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionServiceUpdateSubscriptionProcedure,
		svc.UpdateSubscription,
		connect.WithSchema(subscriptionServiceMethods.ByName("UpdateSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionServiceDeleteSubscriptionHandler := connect.NewUnaryHandler(
		SubscriptionServiceDeleteSubscriptionProcedure,
		svc.DeleteSubscription,
		connect.WithSchema(subscriptionServiceMethods.ByName("DeleteSubscription")),
		connect.WithHandlerOptions(opts...),
	)
	subscriptionServiceTestSubscriptionTemplateHandler := connect.NewUnaryHandler(
		SubscriptionServiceTestSubscriptionTemplateProcedure,
		svc.TestSubscriptionTemplate,
		connect.WithSchema(subscriptionServiceMethods.ByName("TestSubscriptionTemplate")),
		connect.WithHandlerOptions(opts...),
	)
	return "/webhook.SubscriptionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SubscriptionServiceCreateSubscriptionProcedure:
			subscriptionServiceCreateSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionServiceGetSubscriptionProcedure:
			subscriptionServiceGetSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionServiceListSubscriptionsProcedure:
			subscriptionServiceListSubscriptionsHandler.ServeHTTP(w, r)
		case SubscriptionServiceUpdateSubscriptionProcedure:
			subscriptionServiceUpdateSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionServiceDeleteSubscriptionProcedure:
			subscriptionServiceDeleteSubscriptionHandler.ServeHTTP(w, r)
		case SubscriptionServiceTestSubscriptionTemplateProcedure:
			subscriptionServiceTestSubscriptionTemplateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSubscriptionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSubscriptionServiceHandler struct{}

func (UnimplementedSubscriptionServiceHandler) CreateSubscription(context.Context, *connect.Request[proto.CreateSubscriptionRequest]) (*connect.Response[proto.CreateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.SubscriptionService.CreateSubscription is not implemented"))
}

func (UnimplementedSubscriptionServiceHandler) GetSubscription(context.Context, *connect.Request[proto.GetSubscriptionRequest]) (*connect.Response[proto.GetSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.SubscriptionService.GetSubscription is not implemented"))
}

func (UnimplementedSubscriptionServiceHandler) ListSubscriptions(context.Context, *connect.Request[proto.ListSubscriptionsRequest]) (*connect.Response[proto.ListSubscriptionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.SubscriptionService.ListSubscriptions is not implemented"))
}

func (UnimplementedSubscriptionServiceHandler) UpdateSubscription(context.Context, *connect.Request[proto.UpdateSubscriptionRequest]) (*connect.Response[proto.UpdateSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.SubscriptionService.UpdateSubscription is not implemented"))
}

func (UnimplementedSubscriptionServiceHandler) DeleteSubscription(context.Context, *connect.Request[proto.DeleteSubscriptionRequest]) (*connect.Response[proto.DeleteSubscriptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.SubscriptionService.DeleteSubscription is not implemented"))
}

func (UnimplementedSubscriptionServiceHandler) TestSubscriptionTemplate(context.Context, *connect.Request[proto.TestSubscriptionTemplateRequest]) (*connect.Response[proto.TestSubscriptionTemplateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.SubscriptionService.TestSubscriptionTemplate is not implemented"))
}

// DeliveryServiceClient is a client for the webhook.DeliveryService service.
type DeliveryServiceClient interface {
	// GetDeliveryStatus retrieves delivery status for specific delivery
	GetDeliveryStatus(context.Context, *connect.Request[proto.GetDeliveryStatusRequest]) (*connect.Response[proto.GetDeliveryStatusResponse], error)
	// ListDeliveries retrieves delivery history with filters
	ListDeliveries(context.Context, *connect.Request[proto.ListDeliveriesRequest]) (*connect.Response[proto.ListDeliveriesResponse], error)
	// RetryDelivery manually retries failed or pending webhook deliveries
	RetryDelivery(context.Context, *connect.Request[proto.RetryDeliveryRequest]) (*connect.Response[proto.RetryDeliveryResponse], error)
	// GetDeliveryAttempts retrieves individual attempt history for a delivery
	GetDeliveryAttempts(context.Context, *connect.Request[proto.GetDeliveryAttemptsRequest]) (*connect.Response[proto.GetDeliveryAttemptsResponse], error)
}

// NewDeliveryServiceClient constructs a client for the webhook.DeliveryService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeliveryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeliveryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deliveryServiceMethods := proto.File_proto_webhook_proto.Services().ByName("DeliveryService").Methods()
	return &deliveryServiceClient{
		getDeliveryStatus: connect.NewClient[proto.GetDeliveryStatusRequest, proto.GetDeliveryStatusResponse](
			httpClient,
			baseURL+DeliveryServiceGetDeliveryStatusProcedure,
			connect.WithSchema(deliveryServiceMethods.ByName("GetDeliveryStatus")),
			connect.WithClientOptions(opts...),
		),
		listDeliveries: connect.NewClient[proto.ListDeliveriesRequest, proto.ListDeliveriesResponse](
			httpClient,
			baseURL+DeliveryServiceListDeliveriesProcedure,
			connect.WithSchema(deliveryServiceMethods.ByName("ListDeliveries")),
			connect.WithClientOptions(opts...),
		),
		retryDelivery: connect.NewClient[proto.RetryDeliveryRequest, proto.RetryDeliveryResponse](
			httpClient,
			baseURL+DeliveryServiceRetryDeliveryProcedure,
			connect.WithSchema(deliveryServiceMethods.ByName("RetryDelivery")),
			connect.WithClientOptions(opts...),
		),
		getDeliveryAttempts: connect.NewClient[proto.GetDeliveryAttemptsRequest, proto.GetDeliveryAttemptsResponse](
			httpClient,
			baseURL+DeliveryServiceGetDeliveryAttemptsProcedure,
			connect.WithSchema(deliveryServiceMethods.ByName("GetDeliveryAttempts")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deliveryServiceClient implements DeliveryServiceClient.
type deliveryServiceClient struct {
	getDeliveryStatus   *connect.Client[proto.GetDeliveryStatusRequest, proto.GetDeliveryStatusResponse]
	listDeliveries      *connect.Client[proto.ListDeliveriesRequest, proto.ListDeliveriesResponse]
	retryDelivery       *connect.Client[proto.RetryDeliveryRequest, proto.RetryDeliveryResponse]
	getDeliveryAttempts *connect.Client[proto.GetDeliveryAttemptsRequest, proto.GetDeliveryAttemptsResponse]
}

// GetDeliveryStatus calls webhook.DeliveryService.GetDeliveryStatus.
func (c *deliveryServiceClient) GetDeliveryStatus(ctx context.Context, req *connect.Request[proto.GetDeliveryStatusRequest]) (*connect.Response[proto.GetDeliveryStatusResponse], error) {
	return c.getDeliveryStatus.CallUnary(ctx, req)
}

// ListDeliveries calls webhook.DeliveryService.ListDeliveries.
func (c *deliveryServiceClient) ListDeliveries(ctx context.Context, req *connect.Request[proto.ListDeliveriesRequest]) (*connect.Response[proto.ListDeliveriesResponse], error) {
	return c.listDeliveries.CallUnary(ctx, req)
}

// RetryDelivery calls webhook.DeliveryService.RetryDelivery.
func (c *deliveryServiceClient) RetryDelivery(ctx context.Context, req *connect.Request[proto.RetryDeliveryRequest]) (*connect.Response[proto.RetryDeliveryResponse], error) {
	return c.retryDelivery.CallUnary(ctx, req)
}

// GetDeliveryAttempts calls webhook.DeliveryService.GetDeliveryAttempts.
func (c *deliveryServiceClient) GetDeliveryAttempts(ctx context.Context, req *connect.Request[proto.GetDeliveryAttemptsRequest]) (*connect.Response[proto.GetDeliveryAttemptsResponse], error) {
	return c.getDeliveryAttempts.CallUnary(ctx, req)
}

// DeliveryServiceHandler is an implementation of the webhook.DeliveryService service.
type DeliveryServiceHandler interface {
	// GetDeliveryStatus retrieves delivery status for specific delivery
	GetDeliveryStatus(context.Context, *connect.Request[proto.GetDeliveryStatusRequest]) (*connect.Response[proto.GetDeliveryStatusResponse], error)
	// ListDeliveries retrieves delivery history with filters
	ListDeliveries(context.Context, *connect.Request[proto.ListDeliveriesRequest]) (*connect.Response[proto.ListDeliveriesResponse], error)
	// RetryDelivery manually retries failed or pending webhook deliveries
	RetryDelivery(context.Context, *connect.Request[proto.RetryDeliveryRequest]) (*connect.Response[proto.RetryDeliveryResponse], error)
	// GetDeliveryAttempts retrieves individual attempt history for a delivery
	GetDeliveryAttempts(context.Context, *connect.Request[proto.GetDeliveryAttemptsRequest]) (*connect.Response[proto.GetDeliveryAttemptsResponse], error)
}

// NewDeliveryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeliveryServiceHandler(svc DeliveryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deliveryServiceMethods := proto.File_proto_webhook_proto.Services().ByName("DeliveryService").Methods()
	deliveryServiceGetDeliveryStatusHandler := connect.NewUnaryHandler(
		DeliveryServiceGetDeliveryStatusProcedure,
		svc.GetDeliveryStatus,
		connect.WithSchema(deliveryServiceMethods.ByName("GetDeliveryStatus")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryServiceListDeliveriesHandler := connect.NewUnaryHandler(
		DeliveryServiceListDeliveriesProcedure,
		svc.ListDeliveries,
		connect.WithSchema(deliveryServiceMethods.ByName("ListDeliveries")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryServiceRetryDeliveryHandler := connect.NewUnaryHandler(
		DeliveryServiceRetryDeliveryProcedure,
		svc.RetryDelivery,
		connect.WithSchema(deliveryServiceMethods.ByName("RetryDelivery")),
		connect.WithHandlerOptions(opts...),
	)
	deliveryServiceGetDeliveryAttemptsHandler := connect.NewUnaryHandler(
		DeliveryServiceGetDeliveryAttemptsProcedure,
		svc.GetDeliveryAttempts,
		connect.WithSchema(deliveryServiceMethods.ByName("GetDeliveryAttempts")),
		connect.WithHandlerOptions(opts...),
	)
	return "/webhook.DeliveryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeliveryServiceGetDeliveryStatusProcedure:
			deliveryServiceGetDeliveryStatusHandler.ServeHTTP(w, r)
		case DeliveryServiceListDeliveriesProcedure:
			deliveryServiceListDeliveriesHandler.ServeHTTP(w, r)
		case DeliveryServiceRetryDeliveryProcedure:
			deliveryServiceRetryDeliveryHandler.ServeHTTP(w, r)
		case DeliveryServiceGetDeliveryAttemptsProcedure:
			deliveryServiceGetDeliveryAttemptsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeliveryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeliveryServiceHandler struct{}

func (UnimplementedDeliveryServiceHandler) GetDeliveryStatus(context.Context, *connect.Request[proto.GetDeliveryStatusRequest]) (*connect.Response[proto.GetDeliveryStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.DeliveryService.GetDeliveryStatus is not implemented"))
}

func (UnimplementedDeliveryServiceHandler) ListDeliveries(context.Context, *connect.Request[proto.ListDeliveriesRequest]) (*connect.Response[proto.ListDeliveriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.DeliveryService.ListDeliveries is not implemented"))
}

func (UnimplementedDeliveryServiceHandler) RetryDelivery(context.Context, *connect.Request[proto.RetryDeliveryRequest]) (*connect.Response[proto.RetryDeliveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.DeliveryService.RetryDelivery is not implemented"))
}

func (UnimplementedDeliveryServiceHandler) GetDeliveryAttempts(context.Context, *connect.Request[proto.GetDeliveryAttemptsRequest]) (*connect.Response[proto.GetDeliveryAttemptsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.DeliveryService.GetDeliveryAttempts is not implemented"))
}

// HealthServiceClient is a client for the webhook.HealthService service.
type HealthServiceClient interface {
	// GetWebhookHealth gets health metrics for a specific webhook
	GetWebhookHealth(context.Context, *connect.Request[proto.GetWebhookHealthRequest]) (*connect.Response[proto.GetWebhookHealthResponse], error)
	// ListWebhooksByHealth lists webhooks filtered by health status
	ListWebhooksByHealth(context.Context, *connect.Request[proto.ListWebhooksByHealthRequest]) (*connect.Response[proto.ListWebhooksByHealthResponse], error)
	// GetHealthSummary gets a summary of webhook health across all namespaces
	GetHealthSummary(context.Context, *connect.Request[proto.GetHealthSummaryRequest]) (*connect.Response[proto.GetHealthSummaryResponse], error)
}

// NewHealthServiceClient constructs a client for the webhook.HealthService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHealthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HealthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	healthServiceMethods := proto.File_proto_webhook_proto.Services().ByName("HealthService").Methods()
	return &healthServiceClient{
		getWebhookHealth: connect.NewClient[proto.GetWebhookHealthRequest, proto.GetWebhookHealthResponse](
			httpClient,
			baseURL+HealthServiceGetWebhookHealthProcedure,
			connect.WithSchema(healthServiceMethods.ByName("GetWebhookHealth")),
			connect.WithClientOptions(opts...),
		),
		listWebhooksByHealth: connect.NewClient[proto.ListWebhooksByHealthRequest, proto.ListWebhooksByHealthResponse](
			httpClient,
			baseURL+HealthServiceListWebhooksByHealthProcedure,
			connect.WithSchema(healthServiceMethods.ByName("ListWebhooksByHealth")),
			connect.WithClientOptions(opts...),
		),
		getHealthSummary: connect.NewClient[proto.GetHealthSummaryRequest, proto.GetHealthSummaryResponse](
			httpClient,
			baseURL+HealthServiceGetHealthSummaryProcedure,
			connect.WithSchema(healthServiceMethods.ByName("GetHealthSummary")),
			connect.WithClientOptions(opts...),
		),
	}
}

// healthServiceClient implements HealthServiceClient.
type healthServiceClient struct {
	getWebhookHealth     *connect.Client[proto.GetWebhookHealthRequest, proto.GetWebhookHealthResponse]
	listWebhooksByHealth *connect.Client[proto.ListWebhooksByHealthRequest, proto.ListWebhooksByHealthResponse]
	getHealthSummary     *connect.Client[proto.GetHealthSummaryRequest, proto.GetHealthSummaryResponse]
}

// GetWebhookHealth calls webhook.HealthService.GetWebhookHealth.
func (c *healthServiceClient) GetWebhookHealth(ctx context.Context, req *connect.Request[proto.GetWebhookHealthRequest]) (*connect.Response[proto.GetWebhookHealthResponse], error) {
	return c.getWebhookHealth.CallUnary(ctx, req)
}

// ListWebhooksByHealth calls webhook.HealthService.ListWebhooksByHealth.
func (c *healthServiceClient) ListWebhooksByHealth(ctx context.Context, req *connect.Request[proto.ListWebhooksByHealthRequest]) (*connect.Response[proto.ListWebhooksByHealthResponse], error) {
	return c.listWebhooksByHealth.CallUnary(ctx, req)
}

// GetHealthSummary calls webhook.HealthService.GetHealthSummary.
func (c *healthServiceClient) GetHealthSummary(ctx context.Context, req *connect.Request[proto.GetHealthSummaryRequest]) (*connect.Response[proto.GetHealthSummaryResponse], error) {
	return c.getHealthSummary.CallUnary(ctx, req)
}

// HealthServiceHandler is an implementation of the webhook.HealthService service.
type HealthServiceHandler interface {
	// GetWebhookHealth gets health metrics for a specific webhook
	GetWebhookHealth(context.Context, *connect.Request[proto.GetWebhookHealthRequest]) (*connect.Response[proto.GetWebhookHealthResponse], error)
	// ListWebhooksByHealth lists webhooks filtered by health status
	ListWebhooksByHealth(context.Context, *connect.Request[proto.ListWebhooksByHealthRequest]) (*connect.Response[proto.ListWebhooksByHealthResponse], error)
	// GetHealthSummary gets a summary of webhook health across all namespaces
	GetHealthSummary(context.Context, *connect.Request[proto.GetHealthSummaryRequest]) (*connect.Response[proto.GetHealthSummaryResponse], error)
}

// NewHealthServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHealthServiceHandler(svc HealthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	healthServiceMethods := proto.File_proto_webhook_proto.Services().ByName("HealthService").Methods()
	healthServiceGetWebhookHealthHandler := connect.NewUnaryHandler(
		HealthServiceGetWebhookHealthProcedure,
		svc.GetWebhookHealth,
		connect.WithSchema(healthServiceMethods.ByName("GetWebhookHealth")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceListWebhooksByHealthHandler := connect.NewUnaryHandler(
		HealthServiceListWebhooksByHealthProcedure,
		svc.ListWebhooksByHealth,
		connect.WithSchema(healthServiceMethods.ByName("ListWebhooksByHealth")),
		connect.WithHandlerOptions(opts...),
	)
	healthServiceGetHealthSummaryHandler := connect.NewUnaryHandler(
		HealthServiceGetHealthSummaryProcedure,
		svc.GetHealthSummary,
		connect.WithSchema(healthServiceMethods.ByName("GetHealthSummary")),
		connect.WithHandlerOptions(opts...),
	)
	return "/webhook.HealthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HealthServiceGetWebhookHealthProcedure:
			healthServiceGetWebhookHealthHandler.ServeHTTP(w, r)
		case HealthServiceListWebhooksByHealthProcedure:
			healthServiceListWebhooksByHealthHandler.ServeHTTP(w, r)
		case HealthServiceGetHealthSummaryProcedure:
			healthServiceGetHealthSummaryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHealthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHealthServiceHandler struct{}

func (UnimplementedHealthServiceHandler) GetWebhookHealth(context.Context, *connect.Request[proto.GetWebhookHealthRequest]) (*connect.Response[proto.GetWebhookHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.HealthService.GetWebhookHealth is not implemented"))
}

func (UnimplementedHealthServiceHandler) ListWebhooksByHealth(context.Context, *connect.Request[proto.ListWebhooksByHealthRequest]) (*connect.Response[proto.ListWebhooksByHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.HealthService.ListWebhooksByHealth is not implemented"))
}

func (UnimplementedHealthServiceHandler) GetHealthSummary(context.Context, *connect.Request[proto.GetHealthSummaryRequest]) (*connect.Response[proto.GetHealthSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("webhook.HealthService.GetHealthSummary is not implemented"))
}
