receivers:
  postgresql:
    endpoint: postgres:5432
    transport: tcp
    username: riveruser
    password: riverpass
    databases:
      - riverqueue
    collection_interval: 2s
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  otlphttp:
    endpoint: https://otlp.nr-data.net
    headers:
      api-key: 5e3b4e254c15831e392a3f88ef6b5a5bFFFFNRAL # Replace with your New Relic One API key

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]