processors:
  resourcedetection:
    detectors: [env, system]
  cumulativetodelta:
  batch:
    send_batch_size: 100
    timeout: 10s

receivers:
  postgresql:
    endpoint: localhost:5432
    transport: tcp
    username: riveruser
    password: riverpass
    databases:
      - riverqueue
    collection_interval: 10s
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  hostmetrics:
    scrapers:
      cpu:
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:

exporters:
  debug:
  otlp/uptrace:
    endpoint: https://otlp.uptrace.dev:4317
    tls: { insecure: false }
    headers:
      uptrace-dsn: 'https://H38a10azMHU9wIsDS3QG3w@api.uptrace.dev?grpc=4317'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/uptrace, debug]
    metrics:
      receivers: [otlp]
      processors: [cumulativetodelta, batch]
      exporters: [otlp/uptrace, debug]
    metrics/host:
      receivers: [hostmetrics]
      processors: [cumulativetodelta, batch, resourcedetection]
      exporters: [otlp/uptrace, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/uptrace, debug]