global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 5s
    
  - job_name: 'sparrow'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Adjust if sparrow runs on different port
    scrape_interval: 10s
    metrics_path: /metrics