apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sparrow.fullname" . }}
  labels:
    {{- include "sparrow.labels" . | nindent 4 }}
data:
  SPARROW_SERVE_UI: {{ .Values.sparrow.serveUI | quote }}
  ENVIRONMENT: {{ .Values.sparrow.environment | quote }}
  {{- if .Values.sparrow.corsAllowedOrigins }}
  CORS_ALLOWED_ORIGINS: {{ .Values.sparrow.corsAllowedOrigins | quote }}
  {{- end }}
