{{- if not .Values.secrets.existingSecret -}}
{{- if not .Values.secrets.encryptionKeys -}}
{{ fail "set secrets.encryptionKeys unless secrets.existingSecret is used" }}
{{- end -}}
{{- if not .Values.secrets.encryptionPrimaryKeyID -}}
{{ fail "set secrets.encryptionPrimaryKeyID unless secrets.existingSecret is used" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sparrow.fullname" . }}
  labels:
    {{- include "sparrow.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.postgresql.enabled (not .Values.secrets.databaseURL) }}
  DATABASE_URL: {{ include "sparrow.postgresql.url" . | b64enc | quote }}
  {{- else }}
  DATABASE_URL: {{ .Values.secrets.databaseURL | b64enc | quote }}
  {{- end }}
  SPARROW_ENCRYPTION_KEYS: {{ .Values.secrets.encryptionKeys | b64enc | quote }}
  SPARROW_ENCRYPTION_PRIMARY_KEY_ID: {{ .Values.secrets.encryptionPrimaryKeyID | b64enc | quote }}
  {{- if .Values.secrets.apiKey }}
  SPARROW_API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  {{- end }}
{{- end }}
