#!/usr/bin/env node
// Derives the YouTube listing (chapters with valid ≥10s spacing) and an SRT
// caption file from src/explainer/timing.json, so they can never drift from
// the cut. Writes explainer/YOUTUBE.md and explainer/captions.srt.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const t = JSON.parse(readFileSync(join(root, "src/explainer/timing.json"), "utf8"));
const FPS = 30, X = 15;
const sf = (i) => Math.ceil(t.frames[i].duration * FPS) + (i < t.frames.length - 1 ? X : 0);
const starts = [];
let s = 0;
for (let i = 0; i < t.frames.length; i++) { starts.push(s); s += sf(i) - X; }
const total = s + X;

const TITLES = {
  "01-hook": "Webhooks, again",
  "02-pain": "The DIY stack vs. just Postgres",
  "03-three": "Three nights of one webhook",
  "04-happy": "Night one — push, fan-out, signed delivery",
  "05-verify": "Your customer verifies it (9 languages)",
  "06-night": "Night two — 503s, backoff, 429, health, one-shot retry",
  "07-tuesday": "Night three — re-push a day, pause/resume, portal",
  "08-recipes": "Shape the request: Go templates, secret headers, any HTTP API, recipes",
  "09-seeing": "Embedded dashboard + OpenTelemetry",
  "10-needs": "What it needs: just PostgreSQL, MIT",
  "11-compare": "How it compares: Svix, Convoy, Hookdeck, DIY",
  "12-takeaway": "Push once. Sparrow does the rest.",
  "13-cta": "Get started",
};
const mmss = (fr) => { const sec = Math.floor(fr / FPS); return `${Math.floor(sec / 60)}:${String(sec % 60).padStart(2, "0")}`; };

// YouTube needs ≥3 chapters, first at 0:00, each ≥10s. Merge short ones forward.
const chapters = [];
t.frames.forEach((f, i) => {
  const start = i === 0 ? 0 : starts[i];
  const prev = chapters[chapters.length - 1];
  if (prev && start - prev.start < 10 * FPS) { prev.title += " · " + TITLES[f.id]; return; }
  chapters.push({ start, title: TITLES[f.id] });
});
// the last chapter must also be ≥10s
while (chapters.length > 1 && total - chapters[chapters.length - 1].start < 10 * FPS) {
  const last = chapters.pop();
  chapters[chapters.length - 1].title += " · " + last.title;
}

const description = `Sparrow is open-source webhook delivery you run yourself: one Go binary, one PostgreSQL database, MIT licensed. This video follows a single event, item.shipped, through three nights: the happy path, the night a partner went dark, and the Tuesday a deploy shipped a bug.

🚀 Get started
curl -O https://raw.githubusercontent.com/sarathsp06/sparrow/main/deploy/docker-compose.yml
docker compose up -d
Docs: https://sarathsp06.github.io/sparrow/
GitHub: https://github.com/sarathsp06/sparrow

⏱ Chapters
${chapters.map((c) => `${mmss(c.start)} ${c.title}`).join("\n")}

✅ At-least-once delivery with exponential backoff, Retry-After honoured
✅ Standard Webhooks signing — HMAC-SHA256 or Ed25519, verify helpers in 9 languages
✅ Secrets envelope-encrypted at rest (AES-256-GCM)
✅ Go-template payload transforms + prebuilt recipes
✅ Bulk retry and re-push from a deterministic snapshot; pause/resume a webhook
✅ Per-webhook health with email alerts
✅ Embedded dashboard + self-service consumer portal
✅ OpenTelemetry traces, metrics and logs
✅ No Redis, no broker — the River queue runs in PostgreSQL

Comparison is a directional snapshot — vendors change packaging often; verify against their docs.

#webhooks #opensource #golang #postgresql`;

const md = `# YouTube listing (generated by scripts/youtube.mjs — do not hand-edit)

**Title:** Stop Losing Webhooks: Sparrow, Open-Source Webhook Delivery on Postgres

**Tags:** webhooks, webhook delivery, self-hosted webhooks, opensource, go, golang, postgresql, sparrow, svix alternative, standard webhooks

**Total length:** ${mmss(total)}

## Description

\`\`\`
${description}
\`\`\`

Captions: upload \`explainer/captions.srt\` (exact narration; auto-captions mangle Ed25519, HMAC, 429).
`;
writeFileSync(join(root, "explainer/YOUTUBE.md"), md);

// SRT
const ts = (fr) => { const ms = Math.round((fr / FPS) * 1000); const h = Math.floor(ms / 3600000), m = Math.floor(ms / 60000) % 60, sec = Math.floor(ms / 1000) % 60, mss = ms % 1000; return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")},${String(mss).padStart(3, "0")}`; };
let n = 0;
const srt = t.frames.flatMap((f, i) => f.cues.map((c) => {
  const a = starts[i] + Math.round(c.start * FPS);
  const b = a + Math.round(c.dur * FPS) + 6;
  return `${++n}\n${ts(a)} --> ${ts(b)}\n${c.text}\n`;
})).join("\n");
writeFileSync(join(root, "explainer/captions.srt"), srt);
console.log(md);
