// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/opentelemetry.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package webhooks

//go:generate gowrap gen -p github.com/sarathsp06/sparrow/internal/webhooks -i WebhookServiceInterface -t ../../templates/opentelemetry.tmpl -o WebhookServiceInterface_otel.go -l ""

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/sarathsp06/sparrow/internal/webhooks/store"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	_codes "go.opentelemetry.io/otel/codes"
)

// WebhookServiceInterfaceWithTracing implements WebhookServiceInterface interface instrumented with open telemetry spans
type WebhookServiceInterfaceWithTracing struct {
	WebhookServiceInterface
	_instance      string
	_spanDecorator func(span trace.Span, params, results map[string]any)
}

// NewWebhookServiceInterfaceWithTracing returns WebhookServiceInterfaceWithTracing
func NewWebhookServiceInterfaceWithTracing(base WebhookServiceInterface, instance string, spanDecorator ...func(span trace.Span, params, results map[string]any)) WebhookServiceInterfaceWithTracing {
	d := WebhookServiceInterfaceWithTracing{
		WebhookServiceInterface: base,
		_instance:               instance,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// CancelRepush implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) CancelRepush(ctx context.Context, repushID string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.CancelRepush")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"repushID": repushID}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.CancelRepush(ctx, repushID)
}

// CancelRetry implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) CancelRetry(ctx context.Context, retryID string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.CancelRetry")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"retryID": retryID}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.CancelRetry(ctx, retryID)
}

// CreateAlertConfig implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) CreateAlertConfig(ctx context.Context, consumer string, webhookID string, email string, eventTypes []string) (ap1 *store.AlertConfig, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.CreateAlertConfig")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"consumer":   consumer,
				"webhookID":  webhookID,
				"email":      email,
				"eventTypes": eventTypes}, map[string]interface{}{
				"ap1": ap1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.CreateAlertConfig(ctx, consumer, webhookID, email, eventTypes)
}

// CreateSubscription implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) CreateSubscription(ctx context.Context, webhookID string, eventName string, consumer string, headers map[string]string, method string, timeout int, transformEnabled bool, transformTemplate string, labelFilters map[string]string) (s1 string, t1 time.Time, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.CreateSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":               ctx,
				"webhookID":         webhookID,
				"eventName":         eventName,
				"consumer":          consumer,
				"headers":           headers,
				"method":            method,
				"timeout":           timeout,
				"transformEnabled":  transformEnabled,
				"transformTemplate": transformTemplate,
				"labelFilters":      labelFilters}, map[string]interface{}{
				"s1":  s1,
				"t1":  t1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.CreateSubscription(ctx, webhookID, eventName, consumer, headers, method, timeout, transformEnabled, transformTemplate, labelFilters)
}

// CreateWebhook implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) CreateWebhook(ctx context.Context, req WebhookRegistrationRequest) (wp1 *WebhookRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.CreateWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx,
				"req": req}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.CreateWebhook(ctx, req)
}

// DeleteAlertConfig implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) DeleteAlertConfig(ctx context.Context, consumer string, id string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.DeleteAlertConfig")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"consumer": consumer,
				"id":       id}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.DeleteAlertConfig(ctx, consumer, id)
}

// DeleteEvent implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) DeleteEvent(ctx context.Context, name string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.DeleteEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"name": name}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.DeleteEvent(ctx, name)
}

// DeleteSubscription implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) DeleteSubscription(ctx context.Context, subscriptionID string, consumer string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.DeleteSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"subscriptionID": subscriptionID,
				"consumer":       consumer}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.DeleteSubscription(ctx, subscriptionID, consumer)
}

// GetConsumerStats implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetConsumerStats(ctx context.Context, consumer string) (cp1 *ConsumerStatsData, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetConsumerStats")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"consumer": consumer}, map[string]interface{}{
				"cp1": cp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetConsumerStats(ctx, consumer)
}

// GetDeliveryAttempts implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetDeliveryAttempts(ctx context.Context, deliveryID string) (wpa1 []*store.WebhookHealthEvent, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetDeliveryAttempts")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"deliveryID": deliveryID}, map[string]interface{}{
				"wpa1": wpa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetDeliveryAttempts(ctx, deliveryID)
}

// GetDeliveryStatus implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetDeliveryStatus(ctx context.Context, deliveryID string, consumer string) (wp1 *store.WebhookDelivery, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetDeliveryStatus")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"deliveryID": deliveryID,
				"consumer":   consumer}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetDeliveryStatus(ctx, deliveryID, consumer)
}

// GetEvent implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetEvent(ctx context.Context, name string) (ep1 *store.EventRegistration, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":  ctx,
				"name": name}, map[string]interface{}{
				"ep1": ep1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetEvent(ctx, name)
}

// GetEventRecord implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetEventRecord(ctx context.Context, eventID string) (ep1 *store.EventRecord, i1 int32, i2 int32, i3 int32, i4 int32, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetEventRecord")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"eventID": eventID}, map[string]interface{}{
				"ep1": ep1,
				"i1":  i1,
				"i2":  i2,
				"i3":  i3,
				"i4":  i4,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetEventRecord(ctx, eventID)
}

// GetHealthSummary implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetHealthSummary(ctx context.Context) (hp1 *HealthSummaryData, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetHealthSummary")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx": ctx}, map[string]interface{}{
				"hp1": hp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetHealthSummary(ctx)
}

// GetRepushStatus implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetRepushStatus(ctx context.Context, repushID string) (bp1 *store.BatchJob, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetRepushStatus")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"repushID": repushID}, map[string]interface{}{
				"bp1": bp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetRepushStatus(ctx, repushID)
}

// GetRetryStatus implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetRetryStatus(ctx context.Context, retryID string) (bp1 *store.BatchJob, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetRetryStatus")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"retryID": retryID}, map[string]interface{}{
				"bp1": bp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetRetryStatus(ctx, retryID)
}

// GetSubscription implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetSubscription(ctx context.Context, subscriptionID string, consumer string) (ep1 *store.EventSubscription, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"subscriptionID": subscriptionID,
				"consumer":       consumer}, map[string]interface{}{
				"ep1": ep1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetSubscription(ctx, subscriptionID, consumer)
}

// GetWebhookHealth implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) GetWebhookHealth(ctx context.Context, webhookID string, consumer string) (wp1 *WebhookHealthData, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.GetWebhookHealth")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"consumer":  consumer}, map[string]interface{}{
				"wp1": wp1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.GetWebhookHealth(ctx, webhookID, consumer)
}

// ListAlertConfigs implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ListAlertConfigs(ctx context.Context, consumer string, webhookID string) (apa1 []*store.AlertConfig, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ListAlertConfigs")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"consumer":  consumer,
				"webhookID": webhookID}, map[string]interface{}{
				"apa1": apa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ListAlertConfigs(ctx, consumer, webhookID)
}

// ListDeliveries implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ListDeliveries(ctx context.Context, filter store.DeliveryFilter) (wpa1 []*store.WebhookDelivery, i1 int32, s1 string, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ListDeliveries")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"filter": filter}, map[string]interface{}{
				"wpa1": wpa1,
				"i1":   i1,
				"s1":   s1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ListDeliveries(ctx, filter)
}

// ListEventReports implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ListEventReports(ctx context.Context, filter store.EventReportFilter) (epa1 []*store.EventReportWithStats, i1 int32, s1 string, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ListEventReports")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":    ctx,
				"filter": filter}, map[string]interface{}{
				"epa1": epa1,
				"i1":   i1,
				"s1":   s1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ListEventReports(ctx, filter)
}

// ListEvents implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ListEvents(ctx context.Context, activeOnly bool, limit int32, offset int32) (epa1 []*store.EventRegistration, i1 int32, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ListEvents")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"activeOnly": activeOnly,
				"limit":      limit,
				"offset":     offset}, map[string]interface{}{
				"epa1": epa1,
				"i1":   i1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ListEvents(ctx, activeOnly, limit, offset)
}

// ListSubscriptions implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ListSubscriptions(ctx context.Context, consumer string, webhookID string, eventName string, limit int32, offset int32) (epa1 []*store.EventSubscription, i1 int32, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ListSubscriptions")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"consumer":  consumer,
				"webhookID": webhookID,
				"eventName": eventName,
				"limit":     limit,
				"offset":    offset}, map[string]interface{}{
				"epa1": epa1,
				"i1":   i1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ListSubscriptions(ctx, consumer, webhookID, eventName, limit, offset)
}

// ListSubscriptionsByWebhookIDs implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ListSubscriptionsByWebhookIDs(ctx context.Context, webhookIDs []uuid.UUID) (epa1 []*store.EventSubscription, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ListSubscriptionsByWebhookIDs")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"webhookIDs": webhookIDs}, map[string]interface{}{
				"epa1": epa1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ListSubscriptionsByWebhookIDs(ctx, webhookIDs)
}

// ListWebhooks implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ListWebhooks(ctx context.Context, consumer string, webhookID string, event string, activeOnly bool, health string, limit int32, offset int32) (wpa1 []*store.WebhookRegistration, i1 int32, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ListWebhooks")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"consumer":   consumer,
				"webhookID":  webhookID,
				"event":      event,
				"activeOnly": activeOnly,
				"health":     health,
				"limit":      limit,
				"offset":     offset}, map[string]interface{}{
				"wpa1": wpa1,
				"i1":   i1,
				"err":  err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ListWebhooks(ctx, consumer, webhookID, event, activeOnly, health, limit, offset)
}

// PauseWebhook implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) PauseWebhook(ctx context.Context, webhookID string, consumer string, reason string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.PauseWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"consumer":  consumer,
				"reason":    reason}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.PauseWebhook(ctx, webhookID, consumer, reason)
}

// PushEvent implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) PushEvent(ctx context.Context, consumer string, event string, payload map[string]any, ttlSeconds int64, metadata map[string]string, labels map[string]string, idempotencyKey *string) (eventID string, isDuplicate bool, schemaValid bool, warnings []string, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.PushEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":            ctx,
				"consumer":       consumer,
				"event":          event,
				"payload":        payload,
				"ttlSeconds":     ttlSeconds,
				"metadata":       metadata,
				"labels":         labels,
				"idempotencyKey": idempotencyKey}, map[string]interface{}{
				"eventID":     eventID,
				"isDuplicate": isDuplicate,
				"schemaValid": schemaValid,
				"warnings":    warnings,
				"err":         err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.PushEvent(ctx, consumer, event, payload, ttlSeconds, metadata, labels, idempotencyKey)
}

// RePushEvent implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) RePushEvent(ctx context.Context, eventID string) (s1 string, sa1 []string, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.RePushEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"eventID": eventID}, map[string]interface{}{
				"s1":  s1,
				"sa1": sa1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.RePushEvent(ctx, eventID)
}

// RePushEvents implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) RePushEvents(ctx context.Context, repushID string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.RePushEvents")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":      ctx,
				"repushID": repushID}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.RePushEvents(ctx, repushID)
}

// RegisterEvent implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) RegisterEvent(ctx context.Context, name string, description string, schema map[string]any, metadata map[string]string, active bool) (s1 string, t1 time.Time, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.RegisterEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":         ctx,
				"name":        name,
				"description": description,
				"schema":      schema,
				"metadata":    metadata,
				"active":      active}, map[string]interface{}{
				"s1":  s1,
				"t1":  t1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.RegisterEvent(ctx, name, description, schema, metadata, active)
}

// RegisterWebhook implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) RegisterWebhook(ctx context.Context, consumer string, events []string, url string, headers map[string]string, timeout int, active bool, description string, secretHeaders map[string]string) (s1 string, t1 time.Time, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.RegisterWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":           ctx,
				"consumer":      consumer,
				"events":        events,
				"url":           url,
				"headers":       headers,
				"timeout":       timeout,
				"active":        active,
				"description":   description,
				"secretHeaders": secretHeaders}, map[string]interface{}{
				"s1":  s1,
				"t1":  t1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.RegisterWebhook(ctx, consumer, events, url, headers, timeout, active, description, secretHeaders)
}

// ResumeWebhook implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) ResumeWebhook(ctx context.Context, webhookID string, consumer string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.ResumeWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"consumer":  consumer}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.ResumeWebhook(ctx, webhookID, consumer)
}

// RetryDeliveries implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) RetryDeliveries(ctx context.Context, retryID string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.RetryDeliveries")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":     ctx,
				"retryID": retryID}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.RetryDeliveries(ctx, retryID)
}

// RetryDelivery implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) RetryDelivery(ctx context.Context, consumer string, deliveryID string, webhookID string, force bool) (sa1 []string, i1 int32, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.RetryDelivery")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":        ctx,
				"consumer":   consumer,
				"deliveryID": deliveryID,
				"webhookID":  webhookID,
				"force":      force}, map[string]interface{}{
				"sa1": sa1,
				"i1":  i1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.RetryDelivery(ctx, consumer, deliveryID, webhookID, force)
}

// TestSubscriptionTemplate implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) TestSubscriptionTemplate(ctx context.Context, eventName string, transformTemplate string, consumer string) (s1 string, err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.TestSubscriptionTemplate")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":               ctx,
				"eventName":         eventName,
				"transformTemplate": transformTemplate,
				"consumer":          consumer}, map[string]interface{}{
				"s1":  s1,
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.TestSubscriptionTemplate(ctx, eventName, transformTemplate, consumer)
}

// UnregisterWebhook implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) UnregisterWebhook(ctx context.Context, webhookID string, consumer string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.UnregisterWebhook")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":       ctx,
				"webhookID": webhookID,
				"consumer":  consumer}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.UnregisterWebhook(ctx, webhookID, consumer)
}

// UpdateEvent implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) UpdateEvent(ctx context.Context, name string, description string, schema map[string]any, metadata map[string]string, active bool) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.UpdateEvent")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":         ctx,
				"name":        name,
				"description": description,
				"schema":      schema,
				"metadata":    metadata,
				"active":      active}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.UpdateEvent(ctx, name, description, schema, metadata, active)
}

// UpdateSubscription implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) UpdateSubscription(ctx context.Context, subscriptionID string, consumer string, headers map[string]string, method string, timeout int, transformEnabled bool, transformTemplate string, labelFilters map[string]string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.UpdateSubscription")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":               ctx,
				"subscriptionID":    subscriptionID,
				"consumer":          consumer,
				"headers":           headers,
				"method":            method,
				"timeout":           timeout,
				"transformEnabled":  transformEnabled,
				"transformTemplate": transformTemplate,
				"labelFilters":      labelFilters}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.UpdateSubscription(ctx, subscriptionID, consumer, headers, method, timeout, transformEnabled, transformTemplate, labelFilters)
}

// UpdateWebhookConfig implements WebhookServiceInterface
func (_d WebhookServiceInterfaceWithTracing) UpdateWebhookConfig(ctx context.Context, webhookID string, consumer string, events []string, url string, headers map[string]string, active bool, description string, httpConfig *HTTPConfigUpdate, secretHeaders map[string]string, signatureType string, updateMask []string) (err error) {
	ctx, _span := otel.Tracer(_d._instance).Start(ctx, "WebhookServiceInterface.UpdateWebhookConfig")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(_span, map[string]interface{}{
				"ctx":           ctx,
				"webhookID":     webhookID,
				"consumer":      consumer,
				"events":        events,
				"url":           url,
				"headers":       headers,
				"active":        active,
				"description":   description,
				"httpConfig":    httpConfig,
				"secretHeaders": secretHeaders,
				"signatureType": signatureType,
				"updateMask":    updateMask}, map[string]interface{}{
				"err": err})
		} else if err != nil {
			_span.RecordError(err)
			_span.SetStatus(_codes.Error, err.Error())
			_span.SetAttributes(
				attribute.String("event", "error"),
				attribute.String("message", err.Error()),
			)
		}

		_span.End()
	}()
	return _d.WebhookServiceInterface.UpdateWebhookConfig(ctx, webhookID, consumer, events, url, headers, active, description, httpConfig, secretHeaders, signatureType, updateMask)
}
