// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/webhook.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebhookService_RegisterWebhook_FullMethodName               = "/webhook.WebhookService/RegisterWebhook"
	WebhookService_UnregisterWebhook_FullMethodName             = "/webhook.WebhookService/UnregisterWebhook"
	WebhookService_PushEvent_FullMethodName                     = "/webhook.WebhookService/PushEvent"
	WebhookService_GetWebhookStatus_FullMethodName              = "/webhook.WebhookService/GetWebhookStatus"
	WebhookService_ListWebhooks_FullMethodName                  = "/webhook.WebhookService/ListWebhooks"
	WebhookService_RegisterEvent_FullMethodName                 = "/webhook.WebhookService/RegisterEvent"
	WebhookService_ListEvents_FullMethodName                    = "/webhook.WebhookService/ListEvents"
	WebhookService_UpdateEvent_FullMethodName                   = "/webhook.WebhookService/UpdateEvent"
	WebhookService_DeleteEvent_FullMethodName                   = "/webhook.WebhookService/DeleteEvent"
	WebhookService_GetWebhookHealth_FullMethodName              = "/webhook.WebhookService/GetWebhookHealth"
	WebhookService_ListWebhooksByHealth_FullMethodName          = "/webhook.WebhookService/ListWebhooksByHealth"
	WebhookService_GetHealthSummary_FullMethodName              = "/webhook.WebhookService/GetHealthSummary"
	WebhookService_ResubmitWebhook_FullMethodName               = "/webhook.WebhookService/ResubmitWebhook"
	WebhookService_GetRegisteredWebhooks_FullMethodName         = "/webhook.WebhookService/GetRegisteredWebhooks"
	WebhookService_ListRegisteredWebhooksByEvent_FullMethodName = "/webhook.WebhookService/ListRegisteredWebhooksByEvent"
	WebhookService_GetWebhookDeliveryStatus_FullMethodName      = "/webhook.WebhookService/GetWebhookDeliveryStatus"
	WebhookService_ResendWebhook_FullMethodName                 = "/webhook.WebhookService/ResendWebhook"
	WebhookService_GetWebhookDeliveryHistory_FullMethodName     = "/webhook.WebhookService/GetWebhookDeliveryHistory"
	WebhookService_GetNamespaceStats_FullMethodName             = "/webhook.WebhookService/GetNamespaceStats"
	WebhookService_UpdateWebhookConfig_FullMethodName           = "/webhook.WebhookService/UpdateWebhookConfig"
	WebhookService_PauseWebhook_FullMethodName                  = "/webhook.WebhookService/PauseWebhook"
	WebhookService_ResumeWebhook_FullMethodName                 = "/webhook.WebhookService/ResumeWebhook"
	WebhookService_ListEventReports_FullMethodName              = "/webhook.WebhookService/ListEventReports"
)

// WebhookServiceClient is the client API for WebhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WebhookService handles webhook registration and event pushing
type WebhookServiceClient interface {
	// RegisterWebhook registers a URL for specific events in a namespace
	RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*RegisterWebhookResponse, error)
	// UnregisterWebhook removes a webhook registration
	UnregisterWebhook(ctx context.Context, in *UnregisterWebhookRequest, opts ...grpc.CallOption) (*UnregisterWebhookResponse, error)
	// PushEvent pushes an event that triggers registered webhooks
	PushEvent(ctx context.Context, in *PushEventRequest, opts ...grpc.CallOption) (*PushEventResponse, error)
	// GetWebhookStatus gets the status of webhook deliveries
	GetWebhookStatus(ctx context.Context, in *GetWebhookStatusRequest, opts ...grpc.CallOption) (*GetWebhookStatusResponse, error)
	// ListWebhooks lists all registered webhooks for a namespace
	ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error)
	// RegisterEvent registers a new event type (no namespace required)
	RegisterEvent(ctx context.Context, in *RegisterEventRequest, opts ...grpc.CallOption) (*RegisterEventResponse, error)
	// ListEvents lists all registered event types
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	// UpdateEvent updates an event registration
	UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error)
	// DeleteEvent deletes an event registration
	DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error)
	// Health Management
	// GetWebhookHealth gets health metrics for a specific webhook
	GetWebhookHealth(ctx context.Context, in *GetWebhookHealthRequest, opts ...grpc.CallOption) (*GetWebhookHealthResponse, error)
	// ListWebhooksByHealth lists webhooks filtered by health status
	ListWebhooksByHealth(ctx context.Context, in *ListWebhooksByHealthRequest, opts ...grpc.CallOption) (*ListWebhooksByHealthResponse, error)
	// GetHealthSummary gets a summary of webhook health across all namespaces
	GetHealthSummary(ctx context.Context, in *GetHealthSummaryRequest, opts ...grpc.CallOption) (*GetHealthSummaryResponse, error)
	// ResubmitWebhook manually retries failed or pending webhook deliveries
	ResubmitWebhook(ctx context.Context, in *ResubmitWebhookRequest, opts ...grpc.CallOption) (*ResubmitWebhookResponse, error)
	// Additional webhook management methods
	// GetRegisteredWebhooks retrieves registered webhooks by ID or namespace
	GetRegisteredWebhooks(ctx context.Context, in *GetRegisteredWebhooksRequest, opts ...grpc.CallOption) (*GetRegisteredWebhooksResponse, error)
	// ListRegisteredWebhooksByEvent retrieves webhooks registered for specific events
	ListRegisteredWebhooksByEvent(ctx context.Context, in *ListRegisteredWebhooksByEventRequest, opts ...grpc.CallOption) (*ListRegisteredWebhooksByEventResponse, error)
	// GetWebhookDeliveryStatus retrieves delivery status for specific delivery
	GetWebhookDeliveryStatus(ctx context.Context, in *GetWebhookDeliveryStatusRequest, opts ...grpc.CallOption) (*GetWebhookDeliveryStatusResponse, error)
	// ResendWebhook resends a failed webhook delivery
	ResendWebhook(ctx context.Context, in *ResendWebhookRequest, opts ...grpc.CallOption) (*ResendWebhookResponse, error)
	// GetWebhookDeliveryHistory retrieves delivery history for a webhook
	GetWebhookDeliveryHistory(ctx context.Context, in *GetWebhookDeliveryHistoryRequest, opts ...grpc.CallOption) (*GetWebhookDeliveryHistoryResponse, error)
	// GetNamespaceStats retrieves statistics for a namespace
	GetNamespaceStats(ctx context.Context, in *GetNamespaceStatsRequest, opts ...grpc.CallOption) (*GetNamespaceStatsResponse, error)
	// UpdateWebhookConfig updates webhook configuration
	UpdateWebhookConfig(ctx context.Context, in *UpdateWebhookConfigRequest, opts ...grpc.CallOption) (*UpdateWebhookConfigResponse, error)
	// PauseWebhook temporarily disables a webhook
	PauseWebhook(ctx context.Context, in *PauseWebhookRequest, opts ...grpc.CallOption) (*PauseWebhookResponse, error)
	// ResumeWebhook re-enables a paused webhook
	ResumeWebhook(ctx context.Context, in *ResumeWebhookRequest, opts ...grpc.CallOption) (*ResumeWebhookResponse, error)
	// ListEventReports lists all events in descending order for a given namespace
	ListEventReports(ctx context.Context, in *ListEventReportsRequest, opts ...grpc.CallOption) (*ListEventReportsResponse, error)
}

type webhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebhookServiceClient(cc grpc.ClientConnInterface) WebhookServiceClient {
	return &webhookServiceClient{cc}
}

func (c *webhookServiceClient) RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*RegisterWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_RegisterWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) UnregisterWebhook(ctx context.Context, in *UnregisterWebhookRequest, opts ...grpc.CallOption) (*UnregisterWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_UnregisterWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) PushEvent(ctx context.Context, in *PushEventRequest, opts ...grpc.CallOption) (*PushEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushEventResponse)
	err := c.cc.Invoke(ctx, WebhookService_PushEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookStatus(ctx context.Context, in *GetWebhookStatusRequest, opts ...grpc.CallOption) (*GetWebhookStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookStatusResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListWebhooks(ctx context.Context, in *ListWebhooksRequest, opts ...grpc.CallOption) (*ListWebhooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhooksResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) RegisterEvent(ctx context.Context, in *RegisterEventRequest, opts ...grpc.CallOption) (*RegisterEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterEventResponse)
	err := c.cc.Invoke(ctx, WebhookService_RegisterEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) UpdateEvent(ctx context.Context, in *UpdateEventRequest, opts ...grpc.CallOption) (*UpdateEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEventResponse)
	err := c.cc.Invoke(ctx, WebhookService_UpdateEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) DeleteEvent(ctx context.Context, in *DeleteEventRequest, opts ...grpc.CallOption) (*DeleteEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEventResponse)
	err := c.cc.Invoke(ctx, WebhookService_DeleteEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookHealth(ctx context.Context, in *GetWebhookHealthRequest, opts ...grpc.CallOption) (*GetWebhookHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookHealthResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListWebhooksByHealth(ctx context.Context, in *ListWebhooksByHealthRequest, opts ...grpc.CallOption) (*ListWebhooksByHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWebhooksByHealthResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListWebhooksByHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetHealthSummary(ctx context.Context, in *GetHealthSummaryRequest, opts ...grpc.CallOption) (*GetHealthSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHealthSummaryResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetHealthSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ResubmitWebhook(ctx context.Context, in *ResubmitWebhookRequest, opts ...grpc.CallOption) (*ResubmitWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResubmitWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_ResubmitWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetRegisteredWebhooks(ctx context.Context, in *GetRegisteredWebhooksRequest, opts ...grpc.CallOption) (*GetRegisteredWebhooksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegisteredWebhooksResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetRegisteredWebhooks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListRegisteredWebhooksByEvent(ctx context.Context, in *ListRegisteredWebhooksByEventRequest, opts ...grpc.CallOption) (*ListRegisteredWebhooksByEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRegisteredWebhooksByEventResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListRegisteredWebhooksByEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookDeliveryStatus(ctx context.Context, in *GetWebhookDeliveryStatusRequest, opts ...grpc.CallOption) (*GetWebhookDeliveryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookDeliveryStatusResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookDeliveryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ResendWebhook(ctx context.Context, in *ResendWebhookRequest, opts ...grpc.CallOption) (*ResendWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_ResendWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetWebhookDeliveryHistory(ctx context.Context, in *GetWebhookDeliveryHistoryRequest, opts ...grpc.CallOption) (*GetWebhookDeliveryHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWebhookDeliveryHistoryResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetWebhookDeliveryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) GetNamespaceStats(ctx context.Context, in *GetNamespaceStatsRequest, opts ...grpc.CallOption) (*GetNamespaceStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespaceStatsResponse)
	err := c.cc.Invoke(ctx, WebhookService_GetNamespaceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) UpdateWebhookConfig(ctx context.Context, in *UpdateWebhookConfigRequest, opts ...grpc.CallOption) (*UpdateWebhookConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWebhookConfigResponse)
	err := c.cc.Invoke(ctx, WebhookService_UpdateWebhookConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) PauseWebhook(ctx context.Context, in *PauseWebhookRequest, opts ...grpc.CallOption) (*PauseWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_PauseWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ResumeWebhook(ctx context.Context, in *ResumeWebhookRequest, opts ...grpc.CallOption) (*ResumeWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeWebhookResponse)
	err := c.cc.Invoke(ctx, WebhookService_ResumeWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webhookServiceClient) ListEventReports(ctx context.Context, in *ListEventReportsRequest, opts ...grpc.CallOption) (*ListEventReportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventReportsResponse)
	err := c.cc.Invoke(ctx, WebhookService_ListEventReports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebhookServiceServer is the server API for WebhookService service.
// All implementations must embed UnimplementedWebhookServiceServer
// for forward compatibility.
//
// WebhookService handles webhook registration and event pushing
type WebhookServiceServer interface {
	// RegisterWebhook registers a URL for specific events in a namespace
	RegisterWebhook(context.Context, *RegisterWebhookRequest) (*RegisterWebhookResponse, error)
	// UnregisterWebhook removes a webhook registration
	UnregisterWebhook(context.Context, *UnregisterWebhookRequest) (*UnregisterWebhookResponse, error)
	// PushEvent pushes an event that triggers registered webhooks
	PushEvent(context.Context, *PushEventRequest) (*PushEventResponse, error)
	// GetWebhookStatus gets the status of webhook deliveries
	GetWebhookStatus(context.Context, *GetWebhookStatusRequest) (*GetWebhookStatusResponse, error)
	// ListWebhooks lists all registered webhooks for a namespace
	ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error)
	// RegisterEvent registers a new event type (no namespace required)
	RegisterEvent(context.Context, *RegisterEventRequest) (*RegisterEventResponse, error)
	// ListEvents lists all registered event types
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	// UpdateEvent updates an event registration
	UpdateEvent(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error)
	// DeleteEvent deletes an event registration
	DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error)
	// Health Management
	// GetWebhookHealth gets health metrics for a specific webhook
	GetWebhookHealth(context.Context, *GetWebhookHealthRequest) (*GetWebhookHealthResponse, error)
	// ListWebhooksByHealth lists webhooks filtered by health status
	ListWebhooksByHealth(context.Context, *ListWebhooksByHealthRequest) (*ListWebhooksByHealthResponse, error)
	// GetHealthSummary gets a summary of webhook health across all namespaces
	GetHealthSummary(context.Context, *GetHealthSummaryRequest) (*GetHealthSummaryResponse, error)
	// ResubmitWebhook manually retries failed or pending webhook deliveries
	ResubmitWebhook(context.Context, *ResubmitWebhookRequest) (*ResubmitWebhookResponse, error)
	// Additional webhook management methods
	// GetRegisteredWebhooks retrieves registered webhooks by ID or namespace
	GetRegisteredWebhooks(context.Context, *GetRegisteredWebhooksRequest) (*GetRegisteredWebhooksResponse, error)
	// ListRegisteredWebhooksByEvent retrieves webhooks registered for specific events
	ListRegisteredWebhooksByEvent(context.Context, *ListRegisteredWebhooksByEventRequest) (*ListRegisteredWebhooksByEventResponse, error)
	// GetWebhookDeliveryStatus retrieves delivery status for specific delivery
	GetWebhookDeliveryStatus(context.Context, *GetWebhookDeliveryStatusRequest) (*GetWebhookDeliveryStatusResponse, error)
	// ResendWebhook resends a failed webhook delivery
	ResendWebhook(context.Context, *ResendWebhookRequest) (*ResendWebhookResponse, error)
	// GetWebhookDeliveryHistory retrieves delivery history for a webhook
	GetWebhookDeliveryHistory(context.Context, *GetWebhookDeliveryHistoryRequest) (*GetWebhookDeliveryHistoryResponse, error)
	// GetNamespaceStats retrieves statistics for a namespace
	GetNamespaceStats(context.Context, *GetNamespaceStatsRequest) (*GetNamespaceStatsResponse, error)
	// UpdateWebhookConfig updates webhook configuration
	UpdateWebhookConfig(context.Context, *UpdateWebhookConfigRequest) (*UpdateWebhookConfigResponse, error)
	// PauseWebhook temporarily disables a webhook
	PauseWebhook(context.Context, *PauseWebhookRequest) (*PauseWebhookResponse, error)
	// ResumeWebhook re-enables a paused webhook
	ResumeWebhook(context.Context, *ResumeWebhookRequest) (*ResumeWebhookResponse, error)
	// ListEventReports lists all events in descending order for a given namespace
	ListEventReports(context.Context, *ListEventReportsRequest) (*ListEventReportsResponse, error)
	mustEmbedUnimplementedWebhookServiceServer()
}

// UnimplementedWebhookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebhookServiceServer struct{}

func (UnimplementedWebhookServiceServer) RegisterWebhook(context.Context, *RegisterWebhookRequest) (*RegisterWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) UnregisterWebhook(context.Context, *UnregisterWebhookRequest) (*UnregisterWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) PushEvent(context.Context, *PushEventRequest) (*PushEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushEvent not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookStatus(context.Context, *GetWebhookStatusRequest) (*GetWebhookStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhookStatus not implemented")
}
func (UnimplementedWebhookServiceServer) ListWebhooks(context.Context, *ListWebhooksRequest) (*ListWebhooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebhooks not implemented")
}
func (UnimplementedWebhookServiceServer) RegisterEvent(context.Context, *RegisterEventRequest) (*RegisterEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterEvent not implemented")
}
func (UnimplementedWebhookServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedWebhookServiceServer) UpdateEvent(context.Context, *UpdateEventRequest) (*UpdateEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (UnimplementedWebhookServiceServer) DeleteEvent(context.Context, *DeleteEventRequest) (*DeleteEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookHealth(context.Context, *GetWebhookHealthRequest) (*GetWebhookHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhookHealth not implemented")
}
func (UnimplementedWebhookServiceServer) ListWebhooksByHealth(context.Context, *ListWebhooksByHealthRequest) (*ListWebhooksByHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWebhooksByHealth not implemented")
}
func (UnimplementedWebhookServiceServer) GetHealthSummary(context.Context, *GetHealthSummaryRequest) (*GetHealthSummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthSummary not implemented")
}
func (UnimplementedWebhookServiceServer) ResubmitWebhook(context.Context, *ResubmitWebhookRequest) (*ResubmitWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResubmitWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) GetRegisteredWebhooks(context.Context, *GetRegisteredWebhooksRequest) (*GetRegisteredWebhooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredWebhooks not implemented")
}
func (UnimplementedWebhookServiceServer) ListRegisteredWebhooksByEvent(context.Context, *ListRegisteredWebhooksByEventRequest) (*ListRegisteredWebhooksByEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRegisteredWebhooksByEvent not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookDeliveryStatus(context.Context, *GetWebhookDeliveryStatusRequest) (*GetWebhookDeliveryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhookDeliveryStatus not implemented")
}
func (UnimplementedWebhookServiceServer) ResendWebhook(context.Context, *ResendWebhookRequest) (*ResendWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResendWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) GetWebhookDeliveryHistory(context.Context, *GetWebhookDeliveryHistoryRequest) (*GetWebhookDeliveryHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebhookDeliveryHistory not implemented")
}
func (UnimplementedWebhookServiceServer) GetNamespaceStats(context.Context, *GetNamespaceStatsRequest) (*GetNamespaceStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespaceStats not implemented")
}
func (UnimplementedWebhookServiceServer) UpdateWebhookConfig(context.Context, *UpdateWebhookConfigRequest) (*UpdateWebhookConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWebhookConfig not implemented")
}
func (UnimplementedWebhookServiceServer) PauseWebhook(context.Context, *PauseWebhookRequest) (*PauseWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) ResumeWebhook(context.Context, *ResumeWebhookRequest) (*ResumeWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeWebhook not implemented")
}
func (UnimplementedWebhookServiceServer) ListEventReports(context.Context, *ListEventReportsRequest) (*ListEventReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEventReports not implemented")
}
func (UnimplementedWebhookServiceServer) mustEmbedUnimplementedWebhookServiceServer() {}
func (UnimplementedWebhookServiceServer) testEmbeddedByValue()                        {}

// UnsafeWebhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebhookServiceServer will
// result in compilation errors.
type UnsafeWebhookServiceServer interface {
	mustEmbedUnimplementedWebhookServiceServer()
}

func RegisterWebhookServiceServer(s grpc.ServiceRegistrar, srv WebhookServiceServer) {
	// If the following call pancis, it indicates UnimplementedWebhookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebhookService_ServiceDesc, srv)
}

func _WebhookService_RegisterWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).RegisterWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_RegisterWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).RegisterWebhook(ctx, req.(*RegisterWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_UnregisterWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).UnregisterWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_UnregisterWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).UnregisterWebhook(ctx, req.(*UnregisterWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_PushEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).PushEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_PushEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).PushEvent(ctx, req.(*PushEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookStatus(ctx, req.(*GetWebhookStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListWebhooks(ctx, req.(*ListWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_RegisterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).RegisterEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_RegisterEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).RegisterEvent(ctx, req.(*RegisterEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_UpdateEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).UpdateEvent(ctx, req.(*UpdateEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_DeleteEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).DeleteEvent(ctx, req.(*DeleteEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookHealth(ctx, req.(*GetWebhookHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListWebhooksByHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWebhooksByHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListWebhooksByHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListWebhooksByHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListWebhooksByHealth(ctx, req.(*ListWebhooksByHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetHealthSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetHealthSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetHealthSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetHealthSummary(ctx, req.(*GetHealthSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ResubmitWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResubmitWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ResubmitWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ResubmitWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ResubmitWebhook(ctx, req.(*ResubmitWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetRegisteredWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegisteredWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetRegisteredWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetRegisteredWebhooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetRegisteredWebhooks(ctx, req.(*GetRegisteredWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListRegisteredWebhooksByEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRegisteredWebhooksByEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListRegisteredWebhooksByEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListRegisteredWebhooksByEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListRegisteredWebhooksByEvent(ctx, req.(*ListRegisteredWebhooksByEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookDeliveryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookDeliveryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookDeliveryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookDeliveryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookDeliveryStatus(ctx, req.(*GetWebhookDeliveryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ResendWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ResendWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ResendWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ResendWebhook(ctx, req.(*ResendWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetWebhookDeliveryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebhookDeliveryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetWebhookDeliveryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetWebhookDeliveryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetWebhookDeliveryHistory(ctx, req.(*GetWebhookDeliveryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_GetNamespaceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).GetNamespaceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_GetNamespaceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).GetNamespaceStats(ctx, req.(*GetNamespaceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_UpdateWebhookConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebhookConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).UpdateWebhookConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_UpdateWebhookConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).UpdateWebhookConfig(ctx, req.(*UpdateWebhookConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_PauseWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).PauseWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_PauseWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).PauseWebhook(ctx, req.(*PauseWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ResumeWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ResumeWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ResumeWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ResumeWebhook(ctx, req.(*ResumeWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebhookService_ListEventReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebhookServiceServer).ListEventReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebhookService_ListEventReports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebhookServiceServer).ListEventReports(ctx, req.(*ListEventReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebhookService_ServiceDesc is the grpc.ServiceDesc for WebhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "webhook.WebhookService",
	HandlerType: (*WebhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWebhook",
			Handler:    _WebhookService_RegisterWebhook_Handler,
		},
		{
			MethodName: "UnregisterWebhook",
			Handler:    _WebhookService_UnregisterWebhook_Handler,
		},
		{
			MethodName: "PushEvent",
			Handler:    _WebhookService_PushEvent_Handler,
		},
		{
			MethodName: "GetWebhookStatus",
			Handler:    _WebhookService_GetWebhookStatus_Handler,
		},
		{
			MethodName: "ListWebhooks",
			Handler:    _WebhookService_ListWebhooks_Handler,
		},
		{
			MethodName: "RegisterEvent",
			Handler:    _WebhookService_RegisterEvent_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _WebhookService_ListEvents_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _WebhookService_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _WebhookService_DeleteEvent_Handler,
		},
		{
			MethodName: "GetWebhookHealth",
			Handler:    _WebhookService_GetWebhookHealth_Handler,
		},
		{
			MethodName: "ListWebhooksByHealth",
			Handler:    _WebhookService_ListWebhooksByHealth_Handler,
		},
		{
			MethodName: "GetHealthSummary",
			Handler:    _WebhookService_GetHealthSummary_Handler,
		},
		{
			MethodName: "ResubmitWebhook",
			Handler:    _WebhookService_ResubmitWebhook_Handler,
		},
		{
			MethodName: "GetRegisteredWebhooks",
			Handler:    _WebhookService_GetRegisteredWebhooks_Handler,
		},
		{
			MethodName: "ListRegisteredWebhooksByEvent",
			Handler:    _WebhookService_ListRegisteredWebhooksByEvent_Handler,
		},
		{
			MethodName: "GetWebhookDeliveryStatus",
			Handler:    _WebhookService_GetWebhookDeliveryStatus_Handler,
		},
		{
			MethodName: "ResendWebhook",
			Handler:    _WebhookService_ResendWebhook_Handler,
		},
		{
			MethodName: "GetWebhookDeliveryHistory",
			Handler:    _WebhookService_GetWebhookDeliveryHistory_Handler,
		},
		{
			MethodName: "GetNamespaceStats",
			Handler:    _WebhookService_GetNamespaceStats_Handler,
		},
		{
			MethodName: "UpdateWebhookConfig",
			Handler:    _WebhookService_UpdateWebhookConfig_Handler,
		},
		{
			MethodName: "PauseWebhook",
			Handler:    _WebhookService_PauseWebhook_Handler,
		},
		{
			MethodName: "ResumeWebhook",
			Handler:    _WebhookService_ResumeWebhook_Handler,
		},
		{
			MethodName: "ListEventReports",
			Handler:    _WebhookService_ListEventReports_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/webhook.proto",
}
